// Copyright (c) 2018-2021 Zededa, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by go-swagger; DO NOT EDIT.

package artifact_manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/zededa/zedcloud-api/swagger_models"
)

// GetArtifactStreamReader is a Reader for the GetArtifactStream structure.
type GetArtifactStreamReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetArtifactStreamReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetArtifactStreamOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 206:
		result := NewGetArtifactStreamPartialContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 307:
		result := NewGetArtifactStreamTemporaryRedirect()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 400:
		result := NewGetArtifactStreamBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetArtifactStreamUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetArtifactStreamForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetArtifactStreamInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 504:
		result := NewGetArtifactStreamGatewayTimeout()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetArtifactStreamOK creates a GetArtifactStreamOK with default headers values
func NewGetArtifactStreamOK() *GetArtifactStreamOK {
	return &GetArtifactStreamOK{}
}

/* GetArtifactStreamOK describes a response with status code 200, with default header values.

artifact chunk data(streaming responses)
*/
type GetArtifactStreamOK struct {
	Payload strfmt.Base64
}

func (o *GetArtifactStreamOK) Error() string {
	return fmt.Sprintf("[GET /v1/artifacts/id/{id}][%d] getArtifactStreamOK  %+v", 200, o.Payload)
}
func (o *GetArtifactStreamOK) GetPayload() strfmt.Base64 {
	return o.Payload
}

func (o *GetArtifactStreamOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetArtifactStreamPartialContent creates a GetArtifactStreamPartialContent with default headers values
func NewGetArtifactStreamPartialContent() *GetArtifactStreamPartialContent {
	return &GetArtifactStreamPartialContent{}
}

/* GetArtifactStreamPartialContent describes a response with status code 206, with default header values.

Partial Content. The API gateway has fulfilled the partial GET request for the resource.
*/
type GetArtifactStreamPartialContent struct {
	Payload *swagger_models.ZsrvResponse
}

func (o *GetArtifactStreamPartialContent) Error() string {
	return fmt.Sprintf("[GET /v1/artifacts/id/{id}][%d] getArtifactStreamPartialContent  %+v", 206, o.Payload)
}
func (o *GetArtifactStreamPartialContent) GetPayload() *swagger_models.ZsrvResponse {
	return o.Payload
}

func (o *GetArtifactStreamPartialContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(swagger_models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetArtifactStreamTemporaryRedirect creates a GetArtifactStreamTemporaryRedirect with default headers values
func NewGetArtifactStreamTemporaryRedirect() *GetArtifactStreamTemporaryRedirect {
	return &GetArtifactStreamTemporaryRedirect{}
}

/* GetArtifactStreamTemporaryRedirect describes a response with status code 307, with default header values.

Temporary Redirect. Returned when the requested artifactId is not available at the requested time
*/
type GetArtifactStreamTemporaryRedirect struct {
	Payload *swagger_models.ZsrvResponse
}

func (o *GetArtifactStreamTemporaryRedirect) Error() string {
	return fmt.Sprintf("[GET /v1/artifacts/id/{id}][%d] getArtifactStreamTemporaryRedirect  %+v", 307, o.Payload)
}
func (o *GetArtifactStreamTemporaryRedirect) GetPayload() *swagger_models.ZsrvResponse {
	return o.Payload
}

func (o *GetArtifactStreamTemporaryRedirect) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(swagger_models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetArtifactStreamBadRequest creates a GetArtifactStreamBadRequest with default headers values
func NewGetArtifactStreamBadRequest() *GetArtifactStreamBadRequest {
	return &GetArtifactStreamBadRequest{}
}

/* GetArtifactStreamBadRequest describes a response with status code 400, with default header values.

Bad Request. The API gateway did not process the request because of invalid value of parameters.
*/
type GetArtifactStreamBadRequest struct {
	Payload *swagger_models.ZsrvResponse
}

func (o *GetArtifactStreamBadRequest) Error() string {
	return fmt.Sprintf("[GET /v1/artifacts/id/{id}][%d] getArtifactStreamBadRequest  %+v", 400, o.Payload)
}
func (o *GetArtifactStreamBadRequest) GetPayload() *swagger_models.ZsrvResponse {
	return o.Payload
}

func (o *GetArtifactStreamBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(swagger_models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetArtifactStreamUnauthorized creates a GetArtifactStreamUnauthorized with default headers values
func NewGetArtifactStreamUnauthorized() *GetArtifactStreamUnauthorized {
	return &GetArtifactStreamUnauthorized{}
}

/* GetArtifactStreamUnauthorized describes a response with status code 401, with default header values.

Unauthorized. The API gateway did not process the request because it lacks valid authentication credentials for the target resource. The request header has either no authorization details or an authorization that has been refused.
*/
type GetArtifactStreamUnauthorized struct {
	Payload *swagger_models.ZsrvResponse
}

func (o *GetArtifactStreamUnauthorized) Error() string {
	return fmt.Sprintf("[GET /v1/artifacts/id/{id}][%d] getArtifactStreamUnauthorized  %+v", 401, o.Payload)
}
func (o *GetArtifactStreamUnauthorized) GetPayload() *swagger_models.ZsrvResponse {
	return o.Payload
}

func (o *GetArtifactStreamUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(swagger_models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetArtifactStreamForbidden creates a GetArtifactStreamForbidden with default headers values
func NewGetArtifactStreamForbidden() *GetArtifactStreamForbidden {
	return &GetArtifactStreamForbidden{}
}

/* GetArtifactStreamForbidden describes a response with status code 403, with default header values.

Forbidden. The API gateway did not process the request because the requestor does not have edge-node level access permission for the operation or does not have access scope to the project.
*/
type GetArtifactStreamForbidden struct {
	Payload *swagger_models.ZsrvResponse
}

func (o *GetArtifactStreamForbidden) Error() string {
	return fmt.Sprintf("[GET /v1/artifacts/id/{id}][%d] getArtifactStreamForbidden  %+v", 403, o.Payload)
}
func (o *GetArtifactStreamForbidden) GetPayload() *swagger_models.ZsrvResponse {
	return o.Payload
}

func (o *GetArtifactStreamForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(swagger_models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetArtifactStreamInternalServerError creates a GetArtifactStreamInternalServerError with default headers values
func NewGetArtifactStreamInternalServerError() *GetArtifactStreamInternalServerError {
	return &GetArtifactStreamInternalServerError{}
}

/* GetArtifactStreamInternalServerError describes a response with status code 500, with default header values.

Internal Server Error. The API gateway experienced an unexpected condition. Specific error condition is indicated in error codes.
*/
type GetArtifactStreamInternalServerError struct {
	Payload *swagger_models.ZsrvResponse
}

func (o *GetArtifactStreamInternalServerError) Error() string {
	return fmt.Sprintf("[GET /v1/artifacts/id/{id}][%d] getArtifactStreamInternalServerError  %+v", 500, o.Payload)
}
func (o *GetArtifactStreamInternalServerError) GetPayload() *swagger_models.ZsrvResponse {
	return o.Payload
}

func (o *GetArtifactStreamInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(swagger_models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetArtifactStreamGatewayTimeout creates a GetArtifactStreamGatewayTimeout with default headers values
func NewGetArtifactStreamGatewayTimeout() *GetArtifactStreamGatewayTimeout {
	return &GetArtifactStreamGatewayTimeout{}
}

/* GetArtifactStreamGatewayTimeout describes a response with status code 504, with default header values.

Gateway Timeout. The API gateway did not receive a timely response from an upstream microservice it needed to communicate with in order to complete the request.
*/
type GetArtifactStreamGatewayTimeout struct {
	Payload *swagger_models.ZsrvResponse
}

func (o *GetArtifactStreamGatewayTimeout) Error() string {
	return fmt.Sprintf("[GET /v1/artifacts/id/{id}][%d] getArtifactStreamGatewayTimeout  %+v", 504, o.Payload)
}
func (o *GetArtifactStreamGatewayTimeout) GetPayload() *swagger_models.ZsrvResponse {
	return o.Payload
}

func (o *GetArtifactStreamGatewayTimeout) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(swagger_models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
