// Copyright (c) 2018-2021 Zededa, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by go-swagger; DO NOT EDIT.

package hardware_model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/zededa/zedcloud-api/swagger_models"
)

// HardwareModelDeleteHardwareBrandReader is a Reader for the HardwareModelDeleteHardwareBrand structure.
type HardwareModelDeleteHardwareBrandReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *HardwareModelDeleteHardwareBrandReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewHardwareModelDeleteHardwareBrandOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewHardwareModelDeleteHardwareBrandUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewHardwareModelDeleteHardwareBrandForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewHardwareModelDeleteHardwareBrandNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewHardwareModelDeleteHardwareBrandInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 504:
		result := NewHardwareModelDeleteHardwareBrandGatewayTimeout()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewHardwareModelDeleteHardwareBrandDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewHardwareModelDeleteHardwareBrandOK creates a HardwareModelDeleteHardwareBrandOK with default headers values
func NewHardwareModelDeleteHardwareBrandOK() *HardwareModelDeleteHardwareBrandOK {
	return &HardwareModelDeleteHardwareBrandOK{}
}

/* HardwareModelDeleteHardwareBrandOK describes a response with status code 200, with default header values.

A successful response.
*/
type HardwareModelDeleteHardwareBrandOK struct {
	Payload *swagger_models.ZsrvResponse
}

func (o *HardwareModelDeleteHardwareBrandOK) Error() string {
	return fmt.Sprintf("[DELETE /v1/brands/id/{id}][%d] hardwareModelDeleteHardwareBrandOK  %+v", 200, o.Payload)
}
func (o *HardwareModelDeleteHardwareBrandOK) GetPayload() *swagger_models.ZsrvResponse {
	return o.Payload
}

func (o *HardwareModelDeleteHardwareBrandOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(swagger_models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewHardwareModelDeleteHardwareBrandUnauthorized creates a HardwareModelDeleteHardwareBrandUnauthorized with default headers values
func NewHardwareModelDeleteHardwareBrandUnauthorized() *HardwareModelDeleteHardwareBrandUnauthorized {
	return &HardwareModelDeleteHardwareBrandUnauthorized{}
}

/* HardwareModelDeleteHardwareBrandUnauthorized describes a response with status code 401, with default header values.

Unauthorized. The API gateway did not process the request because it lacks valid authentication credentials for the target resource. The request header has either no authorization details or an authorization that has been refused.
*/
type HardwareModelDeleteHardwareBrandUnauthorized struct {
	Payload *swagger_models.ZsrvResponse
}

func (o *HardwareModelDeleteHardwareBrandUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /v1/brands/id/{id}][%d] hardwareModelDeleteHardwareBrandUnauthorized  %+v", 401, o.Payload)
}
func (o *HardwareModelDeleteHardwareBrandUnauthorized) GetPayload() *swagger_models.ZsrvResponse {
	return o.Payload
}

func (o *HardwareModelDeleteHardwareBrandUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(swagger_models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewHardwareModelDeleteHardwareBrandForbidden creates a HardwareModelDeleteHardwareBrandForbidden with default headers values
func NewHardwareModelDeleteHardwareBrandForbidden() *HardwareModelDeleteHardwareBrandForbidden {
	return &HardwareModelDeleteHardwareBrandForbidden{}
}

/* HardwareModelDeleteHardwareBrandForbidden describes a response with status code 403, with default header values.

Forbidden. The API gateway did not process the request because the requestor does not have edge-node level access permission for the operation or does not have access scope to the project.
*/
type HardwareModelDeleteHardwareBrandForbidden struct {
	Payload *swagger_models.ZsrvResponse
}

func (o *HardwareModelDeleteHardwareBrandForbidden) Error() string {
	return fmt.Sprintf("[DELETE /v1/brands/id/{id}][%d] hardwareModelDeleteHardwareBrandForbidden  %+v", 403, o.Payload)
}
func (o *HardwareModelDeleteHardwareBrandForbidden) GetPayload() *swagger_models.ZsrvResponse {
	return o.Payload
}

func (o *HardwareModelDeleteHardwareBrandForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(swagger_models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewHardwareModelDeleteHardwareBrandNotFound creates a HardwareModelDeleteHardwareBrandNotFound with default headers values
func NewHardwareModelDeleteHardwareBrandNotFound() *HardwareModelDeleteHardwareBrandNotFound {
	return &HardwareModelDeleteHardwareBrandNotFound{}
}

/* HardwareModelDeleteHardwareBrandNotFound describes a response with status code 404, with default header values.

Not Found. The API gateway did not process the request because the requested resource could not be found.
*/
type HardwareModelDeleteHardwareBrandNotFound struct {
	Payload *swagger_models.ZsrvResponse
}

func (o *HardwareModelDeleteHardwareBrandNotFound) Error() string {
	return fmt.Sprintf("[DELETE /v1/brands/id/{id}][%d] hardwareModelDeleteHardwareBrandNotFound  %+v", 404, o.Payload)
}
func (o *HardwareModelDeleteHardwareBrandNotFound) GetPayload() *swagger_models.ZsrvResponse {
	return o.Payload
}

func (o *HardwareModelDeleteHardwareBrandNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(swagger_models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewHardwareModelDeleteHardwareBrandInternalServerError creates a HardwareModelDeleteHardwareBrandInternalServerError with default headers values
func NewHardwareModelDeleteHardwareBrandInternalServerError() *HardwareModelDeleteHardwareBrandInternalServerError {
	return &HardwareModelDeleteHardwareBrandInternalServerError{}
}

/* HardwareModelDeleteHardwareBrandInternalServerError describes a response with status code 500, with default header values.

Internal Server Error. The API gateway experienced an unexpected condition. Specific error condition is indicated in error codes.
*/
type HardwareModelDeleteHardwareBrandInternalServerError struct {
	Payload *swagger_models.ZsrvResponse
}

func (o *HardwareModelDeleteHardwareBrandInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /v1/brands/id/{id}][%d] hardwareModelDeleteHardwareBrandInternalServerError  %+v", 500, o.Payload)
}
func (o *HardwareModelDeleteHardwareBrandInternalServerError) GetPayload() *swagger_models.ZsrvResponse {
	return o.Payload
}

func (o *HardwareModelDeleteHardwareBrandInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(swagger_models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewHardwareModelDeleteHardwareBrandGatewayTimeout creates a HardwareModelDeleteHardwareBrandGatewayTimeout with default headers values
func NewHardwareModelDeleteHardwareBrandGatewayTimeout() *HardwareModelDeleteHardwareBrandGatewayTimeout {
	return &HardwareModelDeleteHardwareBrandGatewayTimeout{}
}

/* HardwareModelDeleteHardwareBrandGatewayTimeout describes a response with status code 504, with default header values.

Gateway Timeout. The API gateway did not receive a timely response from an upstream microservice it needed to communicate with in order to complete the request.
*/
type HardwareModelDeleteHardwareBrandGatewayTimeout struct {
	Payload *swagger_models.ZsrvResponse
}

func (o *HardwareModelDeleteHardwareBrandGatewayTimeout) Error() string {
	return fmt.Sprintf("[DELETE /v1/brands/id/{id}][%d] hardwareModelDeleteHardwareBrandGatewayTimeout  %+v", 504, o.Payload)
}
func (o *HardwareModelDeleteHardwareBrandGatewayTimeout) GetPayload() *swagger_models.ZsrvResponse {
	return o.Payload
}

func (o *HardwareModelDeleteHardwareBrandGatewayTimeout) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(swagger_models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewHardwareModelDeleteHardwareBrandDefault creates a HardwareModelDeleteHardwareBrandDefault with default headers values
func NewHardwareModelDeleteHardwareBrandDefault(code int) *HardwareModelDeleteHardwareBrandDefault {
	return &HardwareModelDeleteHardwareBrandDefault{
		_statusCode: code,
	}
}

/* HardwareModelDeleteHardwareBrandDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type HardwareModelDeleteHardwareBrandDefault struct {
	_statusCode int

	Payload *swagger_models.GooglerpcStatus
}

// Code gets the status code for the hardware model delete hardware brand default response
func (o *HardwareModelDeleteHardwareBrandDefault) Code() int {
	return o._statusCode
}

func (o *HardwareModelDeleteHardwareBrandDefault) Error() string {
	return fmt.Sprintf("[DELETE /v1/brands/id/{id}][%d] HardwareModel_DeleteHardwareBrand default  %+v", o._statusCode, o.Payload)
}
func (o *HardwareModelDeleteHardwareBrandDefault) GetPayload() *swagger_models.GooglerpcStatus {
	return o.Payload
}

func (o *HardwareModelDeleteHardwareBrandDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(swagger_models.GooglerpcStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
