// Copyright (c) 2018-2021 Zededa, Inc.\n// SPDX-License-Identifier: Apache-2.0\n
// Code generated by go-swagger; DO NOT EDIT.

package edge_diagnostics

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/zededa/zedcloud-api/swagger_models"
)

// EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameReader is a Reader for the EdgeDiagnosticsGetDeviceTwinBootstrapConfigByName structure.
type EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewEdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewEdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewEdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewEdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewEdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 405:
		result := NewEdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameMethodNotAllowed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewEdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 504:
		result := NewEdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameGatewayTimeout()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewEdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewEdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameOK creates a EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameOK with default headers values
func NewEdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameOK() *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameOK {
	return &EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameOK{}
}

/*
EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameOK describes a response with status code 200, with default header values.

A successful response.
*/
type EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameOK struct {
	Payload *swagger_models.ConfigServiceResp
}

// IsSuccess returns true when this edge diagnostics get device twin bootstrap config by name o k response has a 2xx status code
func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this edge diagnostics get device twin bootstrap config by name o k response has a 3xx status code
func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this edge diagnostics get device twin bootstrap config by name o k response has a 4xx status code
func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this edge diagnostics get device twin bootstrap config by name o k response has a 5xx status code
func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameOK) IsServerError() bool {
	return false
}

// IsCode returns true when this edge diagnostics get device twin bootstrap config by name o k response a status code equal to that given
func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the edge diagnostics get device twin bootstrap config by name o k response
func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameOK) Code() int {
	return 200
}

func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameOK) Error() string {
	return fmt.Sprintf("[GET /v1/devices/name/{name}/config/bootstrap][%d] edgeDiagnosticsGetDeviceTwinBootstrapConfigByNameOK  %+v", 200, o.Payload)
}

func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameOK) String() string {
	return fmt.Sprintf("[GET /v1/devices/name/{name}/config/bootstrap][%d] edgeDiagnosticsGetDeviceTwinBootstrapConfigByNameOK  %+v", 200, o.Payload)
}

func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameOK) GetPayload() *swagger_models.ConfigServiceResp {
	return o.Payload
}

func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(swagger_models.ConfigServiceResp)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameBadRequest creates a EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameBadRequest with default headers values
func NewEdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameBadRequest() *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameBadRequest {
	return &EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameBadRequest{}
}

/*
EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameBadRequest describes a response with status code 400, with default header values.

Bad Request. The API gateway did not process the request because of missing parameter or invalid value of parameters.
*/
type EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameBadRequest struct {
	Payload *swagger_models.ZsrvResponse
}

// IsSuccess returns true when this edge diagnostics get device twin bootstrap config by name bad request response has a 2xx status code
func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this edge diagnostics get device twin bootstrap config by name bad request response has a 3xx status code
func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this edge diagnostics get device twin bootstrap config by name bad request response has a 4xx status code
func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this edge diagnostics get device twin bootstrap config by name bad request response has a 5xx status code
func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this edge diagnostics get device twin bootstrap config by name bad request response a status code equal to that given
func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the edge diagnostics get device twin bootstrap config by name bad request response
func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameBadRequest) Code() int {
	return 400
}

func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameBadRequest) Error() string {
	return fmt.Sprintf("[GET /v1/devices/name/{name}/config/bootstrap][%d] edgeDiagnosticsGetDeviceTwinBootstrapConfigByNameBadRequest  %+v", 400, o.Payload)
}

func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameBadRequest) String() string {
	return fmt.Sprintf("[GET /v1/devices/name/{name}/config/bootstrap][%d] edgeDiagnosticsGetDeviceTwinBootstrapConfigByNameBadRequest  %+v", 400, o.Payload)
}

func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameBadRequest) GetPayload() *swagger_models.ZsrvResponse {
	return o.Payload
}

func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(swagger_models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameUnauthorized creates a EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameUnauthorized with default headers values
func NewEdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameUnauthorized() *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameUnauthorized {
	return &EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameUnauthorized{}
}

/*
EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameUnauthorized describes a response with status code 401, with default header values.

Unauthorized. The API gateway did not process the request because it lacks valid authentication credentials for the target resource. The request header has either no authorization details or an authorization that has been refused.
*/
type EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameUnauthorized struct {
	Payload *swagger_models.ZsrvResponse
}

// IsSuccess returns true when this edge diagnostics get device twin bootstrap config by name unauthorized response has a 2xx status code
func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this edge diagnostics get device twin bootstrap config by name unauthorized response has a 3xx status code
func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this edge diagnostics get device twin bootstrap config by name unauthorized response has a 4xx status code
func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this edge diagnostics get device twin bootstrap config by name unauthorized response has a 5xx status code
func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this edge diagnostics get device twin bootstrap config by name unauthorized response a status code equal to that given
func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the edge diagnostics get device twin bootstrap config by name unauthorized response
func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameUnauthorized) Code() int {
	return 401
}

func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameUnauthorized) Error() string {
	return fmt.Sprintf("[GET /v1/devices/name/{name}/config/bootstrap][%d] edgeDiagnosticsGetDeviceTwinBootstrapConfigByNameUnauthorized  %+v", 401, o.Payload)
}

func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameUnauthorized) String() string {
	return fmt.Sprintf("[GET /v1/devices/name/{name}/config/bootstrap][%d] edgeDiagnosticsGetDeviceTwinBootstrapConfigByNameUnauthorized  %+v", 401, o.Payload)
}

func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameUnauthorized) GetPayload() *swagger_models.ZsrvResponse {
	return o.Payload
}

func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(swagger_models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameForbidden creates a EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameForbidden with default headers values
func NewEdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameForbidden() *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameForbidden {
	return &EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameForbidden{}
}

/*
EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameForbidden describes a response with status code 403, with default header values.

Forbidden. The API gateway did not process the request because the requestor does not have edge-node level access permission for the operation or does not have access scope to the project.
*/
type EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameForbidden struct {
	Payload *swagger_models.ZsrvResponse
}

// IsSuccess returns true when this edge diagnostics get device twin bootstrap config by name forbidden response has a 2xx status code
func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this edge diagnostics get device twin bootstrap config by name forbidden response has a 3xx status code
func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this edge diagnostics get device twin bootstrap config by name forbidden response has a 4xx status code
func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this edge diagnostics get device twin bootstrap config by name forbidden response has a 5xx status code
func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this edge diagnostics get device twin bootstrap config by name forbidden response a status code equal to that given
func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the edge diagnostics get device twin bootstrap config by name forbidden response
func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameForbidden) Code() int {
	return 403
}

func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameForbidden) Error() string {
	return fmt.Sprintf("[GET /v1/devices/name/{name}/config/bootstrap][%d] edgeDiagnosticsGetDeviceTwinBootstrapConfigByNameForbidden  %+v", 403, o.Payload)
}

func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameForbidden) String() string {
	return fmt.Sprintf("[GET /v1/devices/name/{name}/config/bootstrap][%d] edgeDiagnosticsGetDeviceTwinBootstrapConfigByNameForbidden  %+v", 403, o.Payload)
}

func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameForbidden) GetPayload() *swagger_models.ZsrvResponse {
	return o.Payload
}

func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(swagger_models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameNotFound creates a EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameNotFound with default headers values
func NewEdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameNotFound() *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameNotFound {
	return &EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameNotFound{}
}

/*
EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameNotFound describes a response with status code 404, with default header values.

Not Found. The API gateway did not process the request because the requested resource could not be found.
*/
type EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameNotFound struct {
	Payload *swagger_models.ZsrvResponse
}

// IsSuccess returns true when this edge diagnostics get device twin bootstrap config by name not found response has a 2xx status code
func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this edge diagnostics get device twin bootstrap config by name not found response has a 3xx status code
func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this edge diagnostics get device twin bootstrap config by name not found response has a 4xx status code
func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this edge diagnostics get device twin bootstrap config by name not found response has a 5xx status code
func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this edge diagnostics get device twin bootstrap config by name not found response a status code equal to that given
func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the edge diagnostics get device twin bootstrap config by name not found response
func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameNotFound) Code() int {
	return 404
}

func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameNotFound) Error() string {
	return fmt.Sprintf("[GET /v1/devices/name/{name}/config/bootstrap][%d] edgeDiagnosticsGetDeviceTwinBootstrapConfigByNameNotFound  %+v", 404, o.Payload)
}

func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameNotFound) String() string {
	return fmt.Sprintf("[GET /v1/devices/name/{name}/config/bootstrap][%d] edgeDiagnosticsGetDeviceTwinBootstrapConfigByNameNotFound  %+v", 404, o.Payload)
}

func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameNotFound) GetPayload() *swagger_models.ZsrvResponse {
	return o.Payload
}

func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(swagger_models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameMethodNotAllowed creates a EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameMethodNotAllowed with default headers values
func NewEdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameMethodNotAllowed() *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameMethodNotAllowed {
	return &EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameMethodNotAllowed{}
}

/*
EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameMethodNotAllowed describes a response with status code 405, with default header values.

Method not allowed. The API request can't be performed due to a wrong edge node's admin status.
*/
type EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameMethodNotAllowed struct {
	Payload *swagger_models.ZsrvResponse
}

// IsSuccess returns true when this edge diagnostics get device twin bootstrap config by name method not allowed response has a 2xx status code
func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameMethodNotAllowed) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this edge diagnostics get device twin bootstrap config by name method not allowed response has a 3xx status code
func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameMethodNotAllowed) IsRedirect() bool {
	return false
}

// IsClientError returns true when this edge diagnostics get device twin bootstrap config by name method not allowed response has a 4xx status code
func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameMethodNotAllowed) IsClientError() bool {
	return true
}

// IsServerError returns true when this edge diagnostics get device twin bootstrap config by name method not allowed response has a 5xx status code
func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameMethodNotAllowed) IsServerError() bool {
	return false
}

// IsCode returns true when this edge diagnostics get device twin bootstrap config by name method not allowed response a status code equal to that given
func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameMethodNotAllowed) IsCode(code int) bool {
	return code == 405
}

// Code gets the status code for the edge diagnostics get device twin bootstrap config by name method not allowed response
func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameMethodNotAllowed) Code() int {
	return 405
}

func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameMethodNotAllowed) Error() string {
	return fmt.Sprintf("[GET /v1/devices/name/{name}/config/bootstrap][%d] edgeDiagnosticsGetDeviceTwinBootstrapConfigByNameMethodNotAllowed  %+v", 405, o.Payload)
}

func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameMethodNotAllowed) String() string {
	return fmt.Sprintf("[GET /v1/devices/name/{name}/config/bootstrap][%d] edgeDiagnosticsGetDeviceTwinBootstrapConfigByNameMethodNotAllowed  %+v", 405, o.Payload)
}

func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameMethodNotAllowed) GetPayload() *swagger_models.ZsrvResponse {
	return o.Payload
}

func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameMethodNotAllowed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(swagger_models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameInternalServerError creates a EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameInternalServerError with default headers values
func NewEdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameInternalServerError() *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameInternalServerError {
	return &EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameInternalServerError{}
}

/*
EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameInternalServerError describes a response with status code 500, with default header values.

Internal Server Error. The API gateway experienced an unexpected condition. Specific error condition is indicated in error codes.
*/
type EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameInternalServerError struct {
	Payload *swagger_models.ZsrvResponse
}

// IsSuccess returns true when this edge diagnostics get device twin bootstrap config by name internal server error response has a 2xx status code
func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this edge diagnostics get device twin bootstrap config by name internal server error response has a 3xx status code
func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this edge diagnostics get device twin bootstrap config by name internal server error response has a 4xx status code
func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this edge diagnostics get device twin bootstrap config by name internal server error response has a 5xx status code
func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this edge diagnostics get device twin bootstrap config by name internal server error response a status code equal to that given
func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the edge diagnostics get device twin bootstrap config by name internal server error response
func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameInternalServerError) Code() int {
	return 500
}

func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameInternalServerError) Error() string {
	return fmt.Sprintf("[GET /v1/devices/name/{name}/config/bootstrap][%d] edgeDiagnosticsGetDeviceTwinBootstrapConfigByNameInternalServerError  %+v", 500, o.Payload)
}

func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameInternalServerError) String() string {
	return fmt.Sprintf("[GET /v1/devices/name/{name}/config/bootstrap][%d] edgeDiagnosticsGetDeviceTwinBootstrapConfigByNameInternalServerError  %+v", 500, o.Payload)
}

func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameInternalServerError) GetPayload() *swagger_models.ZsrvResponse {
	return o.Payload
}

func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(swagger_models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameGatewayTimeout creates a EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameGatewayTimeout with default headers values
func NewEdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameGatewayTimeout() *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameGatewayTimeout {
	return &EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameGatewayTimeout{}
}

/*
EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameGatewayTimeout describes a response with status code 504, with default header values.

Gateway Timeout. The API gateway did not receive a timely response from an upstream microservice it needed to communicate with in order to complete the request.
*/
type EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameGatewayTimeout struct {
	Payload *swagger_models.ZsrvResponse
}

// IsSuccess returns true when this edge diagnostics get device twin bootstrap config by name gateway timeout response has a 2xx status code
func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameGatewayTimeout) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this edge diagnostics get device twin bootstrap config by name gateway timeout response has a 3xx status code
func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameGatewayTimeout) IsRedirect() bool {
	return false
}

// IsClientError returns true when this edge diagnostics get device twin bootstrap config by name gateway timeout response has a 4xx status code
func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameGatewayTimeout) IsClientError() bool {
	return false
}

// IsServerError returns true when this edge diagnostics get device twin bootstrap config by name gateway timeout response has a 5xx status code
func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameGatewayTimeout) IsServerError() bool {
	return true
}

// IsCode returns true when this edge diagnostics get device twin bootstrap config by name gateway timeout response a status code equal to that given
func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameGatewayTimeout) IsCode(code int) bool {
	return code == 504
}

// Code gets the status code for the edge diagnostics get device twin bootstrap config by name gateway timeout response
func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameGatewayTimeout) Code() int {
	return 504
}

func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameGatewayTimeout) Error() string {
	return fmt.Sprintf("[GET /v1/devices/name/{name}/config/bootstrap][%d] edgeDiagnosticsGetDeviceTwinBootstrapConfigByNameGatewayTimeout  %+v", 504, o.Payload)
}

func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameGatewayTimeout) String() string {
	return fmt.Sprintf("[GET /v1/devices/name/{name}/config/bootstrap][%d] edgeDiagnosticsGetDeviceTwinBootstrapConfigByNameGatewayTimeout  %+v", 504, o.Payload)
}

func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameGatewayTimeout) GetPayload() *swagger_models.ZsrvResponse {
	return o.Payload
}

func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameGatewayTimeout) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(swagger_models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameDefault creates a EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameDefault with default headers values
func NewEdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameDefault(code int) *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameDefault {
	return &EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameDefault{
		_statusCode: code,
	}
}

/*
EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameDefault struct {
	_statusCode int

	Payload *swagger_models.GooglerpcStatus
}

// IsSuccess returns true when this edge diagnostics get device twin bootstrap config by name default response has a 2xx status code
func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this edge diagnostics get device twin bootstrap config by name default response has a 3xx status code
func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this edge diagnostics get device twin bootstrap config by name default response has a 4xx status code
func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this edge diagnostics get device twin bootstrap config by name default response has a 5xx status code
func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this edge diagnostics get device twin bootstrap config by name default response a status code equal to that given
func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the edge diagnostics get device twin bootstrap config by name default response
func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameDefault) Code() int {
	return o._statusCode
}

func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameDefault) Error() string {
	return fmt.Sprintf("[GET /v1/devices/name/{name}/config/bootstrap][%d] EdgeDiagnostics_GetDeviceTwinBootstrapConfigByName default  %+v", o._statusCode, o.Payload)
}

func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameDefault) String() string {
	return fmt.Sprintf("[GET /v1/devices/name/{name}/config/bootstrap][%d] EdgeDiagnostics_GetDeviceTwinBootstrapConfigByName default  %+v", o._statusCode, o.Payload)
}

func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameDefault) GetPayload() *swagger_models.GooglerpcStatus {
	return o.Payload
}

func (o *EdgeDiagnosticsGetDeviceTwinBootstrapConfigByNameDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(swagger_models.GooglerpcStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
