// Copyright (c) 2018-2021 Zededa, Inc.\n// SPDX-License-Identifier: Apache-2.0\n
// Code generated by go-swagger; DO NOT EDIT.

package edge_diagnostics

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/zededa/zedcloud-api/swagger_models"
)

// EdgeDiagnosticsGetDeviceTwinNextConfigReader is a Reader for the EdgeDiagnosticsGetDeviceTwinNextConfig structure.
type EdgeDiagnosticsGetDeviceTwinNextConfigReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EdgeDiagnosticsGetDeviceTwinNextConfigReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewEdgeDiagnosticsGetDeviceTwinNextConfigOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewEdgeDiagnosticsGetDeviceTwinNextConfigBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewEdgeDiagnosticsGetDeviceTwinNextConfigUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewEdgeDiagnosticsGetDeviceTwinNextConfigForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewEdgeDiagnosticsGetDeviceTwinNextConfigNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewEdgeDiagnosticsGetDeviceTwinNextConfigInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 504:
		result := NewEdgeDiagnosticsGetDeviceTwinNextConfigGatewayTimeout()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewEdgeDiagnosticsGetDeviceTwinNextConfigDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewEdgeDiagnosticsGetDeviceTwinNextConfigOK creates a EdgeDiagnosticsGetDeviceTwinNextConfigOK with default headers values
func NewEdgeDiagnosticsGetDeviceTwinNextConfigOK() *EdgeDiagnosticsGetDeviceTwinNextConfigOK {
	return &EdgeDiagnosticsGetDeviceTwinNextConfigOK{}
}

/*
EdgeDiagnosticsGetDeviceTwinNextConfigOK describes a response with status code 200, with default header values.

A successful response.
*/
type EdgeDiagnosticsGetDeviceTwinNextConfigOK struct {
	Payload *swagger_models.ConfigServiceResp
}

// IsSuccess returns true when this edge diagnostics get device twin next config o k response has a 2xx status code
func (o *EdgeDiagnosticsGetDeviceTwinNextConfigOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this edge diagnostics get device twin next config o k response has a 3xx status code
func (o *EdgeDiagnosticsGetDeviceTwinNextConfigOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this edge diagnostics get device twin next config o k response has a 4xx status code
func (o *EdgeDiagnosticsGetDeviceTwinNextConfigOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this edge diagnostics get device twin next config o k response has a 5xx status code
func (o *EdgeDiagnosticsGetDeviceTwinNextConfigOK) IsServerError() bool {
	return false
}

// IsCode returns true when this edge diagnostics get device twin next config o k response a status code equal to that given
func (o *EdgeDiagnosticsGetDeviceTwinNextConfigOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the edge diagnostics get device twin next config o k response
func (o *EdgeDiagnosticsGetDeviceTwinNextConfigOK) Code() int {
	return 200
}

func (o *EdgeDiagnosticsGetDeviceTwinNextConfigOK) Error() string {
	return fmt.Sprintf("[GET /v1/devices/id/{id}/config/next][%d] edgeDiagnosticsGetDeviceTwinNextConfigOK  %+v", 200, o.Payload)
}

func (o *EdgeDiagnosticsGetDeviceTwinNextConfigOK) String() string {
	return fmt.Sprintf("[GET /v1/devices/id/{id}/config/next][%d] edgeDiagnosticsGetDeviceTwinNextConfigOK  %+v", 200, o.Payload)
}

func (o *EdgeDiagnosticsGetDeviceTwinNextConfigOK) GetPayload() *swagger_models.ConfigServiceResp {
	return o.Payload
}

func (o *EdgeDiagnosticsGetDeviceTwinNextConfigOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(swagger_models.ConfigServiceResp)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEdgeDiagnosticsGetDeviceTwinNextConfigBadRequest creates a EdgeDiagnosticsGetDeviceTwinNextConfigBadRequest with default headers values
func NewEdgeDiagnosticsGetDeviceTwinNextConfigBadRequest() *EdgeDiagnosticsGetDeviceTwinNextConfigBadRequest {
	return &EdgeDiagnosticsGetDeviceTwinNextConfigBadRequest{}
}

/*
EdgeDiagnosticsGetDeviceTwinNextConfigBadRequest describes a response with status code 400, with default header values.

Bad Request. The API gateway did not process the request because of missing parameter or invalid value of parameters.
*/
type EdgeDiagnosticsGetDeviceTwinNextConfigBadRequest struct {
	Payload *swagger_models.ZsrvResponse
}

// IsSuccess returns true when this edge diagnostics get device twin next config bad request response has a 2xx status code
func (o *EdgeDiagnosticsGetDeviceTwinNextConfigBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this edge diagnostics get device twin next config bad request response has a 3xx status code
func (o *EdgeDiagnosticsGetDeviceTwinNextConfigBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this edge diagnostics get device twin next config bad request response has a 4xx status code
func (o *EdgeDiagnosticsGetDeviceTwinNextConfigBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this edge diagnostics get device twin next config bad request response has a 5xx status code
func (o *EdgeDiagnosticsGetDeviceTwinNextConfigBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this edge diagnostics get device twin next config bad request response a status code equal to that given
func (o *EdgeDiagnosticsGetDeviceTwinNextConfigBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the edge diagnostics get device twin next config bad request response
func (o *EdgeDiagnosticsGetDeviceTwinNextConfigBadRequest) Code() int {
	return 400
}

func (o *EdgeDiagnosticsGetDeviceTwinNextConfigBadRequest) Error() string {
	return fmt.Sprintf("[GET /v1/devices/id/{id}/config/next][%d] edgeDiagnosticsGetDeviceTwinNextConfigBadRequest  %+v", 400, o.Payload)
}

func (o *EdgeDiagnosticsGetDeviceTwinNextConfigBadRequest) String() string {
	return fmt.Sprintf("[GET /v1/devices/id/{id}/config/next][%d] edgeDiagnosticsGetDeviceTwinNextConfigBadRequest  %+v", 400, o.Payload)
}

func (o *EdgeDiagnosticsGetDeviceTwinNextConfigBadRequest) GetPayload() *swagger_models.ZsrvResponse {
	return o.Payload
}

func (o *EdgeDiagnosticsGetDeviceTwinNextConfigBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(swagger_models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEdgeDiagnosticsGetDeviceTwinNextConfigUnauthorized creates a EdgeDiagnosticsGetDeviceTwinNextConfigUnauthorized with default headers values
func NewEdgeDiagnosticsGetDeviceTwinNextConfigUnauthorized() *EdgeDiagnosticsGetDeviceTwinNextConfigUnauthorized {
	return &EdgeDiagnosticsGetDeviceTwinNextConfigUnauthorized{}
}

/*
EdgeDiagnosticsGetDeviceTwinNextConfigUnauthorized describes a response with status code 401, with default header values.

Unauthorized. The API gateway did not process the request because it lacks valid authentication credentials for the target resource. The request header has either no authorization details or an authorization that has been refused.
*/
type EdgeDiagnosticsGetDeviceTwinNextConfigUnauthorized struct {
	Payload *swagger_models.ZsrvResponse
}

// IsSuccess returns true when this edge diagnostics get device twin next config unauthorized response has a 2xx status code
func (o *EdgeDiagnosticsGetDeviceTwinNextConfigUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this edge diagnostics get device twin next config unauthorized response has a 3xx status code
func (o *EdgeDiagnosticsGetDeviceTwinNextConfigUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this edge diagnostics get device twin next config unauthorized response has a 4xx status code
func (o *EdgeDiagnosticsGetDeviceTwinNextConfigUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this edge diagnostics get device twin next config unauthorized response has a 5xx status code
func (o *EdgeDiagnosticsGetDeviceTwinNextConfigUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this edge diagnostics get device twin next config unauthorized response a status code equal to that given
func (o *EdgeDiagnosticsGetDeviceTwinNextConfigUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the edge diagnostics get device twin next config unauthorized response
func (o *EdgeDiagnosticsGetDeviceTwinNextConfigUnauthorized) Code() int {
	return 401
}

func (o *EdgeDiagnosticsGetDeviceTwinNextConfigUnauthorized) Error() string {
	return fmt.Sprintf("[GET /v1/devices/id/{id}/config/next][%d] edgeDiagnosticsGetDeviceTwinNextConfigUnauthorized  %+v", 401, o.Payload)
}

func (o *EdgeDiagnosticsGetDeviceTwinNextConfigUnauthorized) String() string {
	return fmt.Sprintf("[GET /v1/devices/id/{id}/config/next][%d] edgeDiagnosticsGetDeviceTwinNextConfigUnauthorized  %+v", 401, o.Payload)
}

func (o *EdgeDiagnosticsGetDeviceTwinNextConfigUnauthorized) GetPayload() *swagger_models.ZsrvResponse {
	return o.Payload
}

func (o *EdgeDiagnosticsGetDeviceTwinNextConfigUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(swagger_models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEdgeDiagnosticsGetDeviceTwinNextConfigForbidden creates a EdgeDiagnosticsGetDeviceTwinNextConfigForbidden with default headers values
func NewEdgeDiagnosticsGetDeviceTwinNextConfigForbidden() *EdgeDiagnosticsGetDeviceTwinNextConfigForbidden {
	return &EdgeDiagnosticsGetDeviceTwinNextConfigForbidden{}
}

/*
EdgeDiagnosticsGetDeviceTwinNextConfigForbidden describes a response with status code 403, with default header values.

Forbidden. The API gateway did not process the request because the requestor does not have edge-node level access permission for the operation or does not have access scope to the project.
*/
type EdgeDiagnosticsGetDeviceTwinNextConfigForbidden struct {
	Payload *swagger_models.ZsrvResponse
}

// IsSuccess returns true when this edge diagnostics get device twin next config forbidden response has a 2xx status code
func (o *EdgeDiagnosticsGetDeviceTwinNextConfigForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this edge diagnostics get device twin next config forbidden response has a 3xx status code
func (o *EdgeDiagnosticsGetDeviceTwinNextConfigForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this edge diagnostics get device twin next config forbidden response has a 4xx status code
func (o *EdgeDiagnosticsGetDeviceTwinNextConfigForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this edge diagnostics get device twin next config forbidden response has a 5xx status code
func (o *EdgeDiagnosticsGetDeviceTwinNextConfigForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this edge diagnostics get device twin next config forbidden response a status code equal to that given
func (o *EdgeDiagnosticsGetDeviceTwinNextConfigForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the edge diagnostics get device twin next config forbidden response
func (o *EdgeDiagnosticsGetDeviceTwinNextConfigForbidden) Code() int {
	return 403
}

func (o *EdgeDiagnosticsGetDeviceTwinNextConfigForbidden) Error() string {
	return fmt.Sprintf("[GET /v1/devices/id/{id}/config/next][%d] edgeDiagnosticsGetDeviceTwinNextConfigForbidden  %+v", 403, o.Payload)
}

func (o *EdgeDiagnosticsGetDeviceTwinNextConfigForbidden) String() string {
	return fmt.Sprintf("[GET /v1/devices/id/{id}/config/next][%d] edgeDiagnosticsGetDeviceTwinNextConfigForbidden  %+v", 403, o.Payload)
}

func (o *EdgeDiagnosticsGetDeviceTwinNextConfigForbidden) GetPayload() *swagger_models.ZsrvResponse {
	return o.Payload
}

func (o *EdgeDiagnosticsGetDeviceTwinNextConfigForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(swagger_models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEdgeDiagnosticsGetDeviceTwinNextConfigNotFound creates a EdgeDiagnosticsGetDeviceTwinNextConfigNotFound with default headers values
func NewEdgeDiagnosticsGetDeviceTwinNextConfigNotFound() *EdgeDiagnosticsGetDeviceTwinNextConfigNotFound {
	return &EdgeDiagnosticsGetDeviceTwinNextConfigNotFound{}
}

/*
EdgeDiagnosticsGetDeviceTwinNextConfigNotFound describes a response with status code 404, with default header values.

Not Found. The API gateway did not process the request because the requested resource could not be found.
*/
type EdgeDiagnosticsGetDeviceTwinNextConfigNotFound struct {
	Payload *swagger_models.ZsrvResponse
}

// IsSuccess returns true when this edge diagnostics get device twin next config not found response has a 2xx status code
func (o *EdgeDiagnosticsGetDeviceTwinNextConfigNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this edge diagnostics get device twin next config not found response has a 3xx status code
func (o *EdgeDiagnosticsGetDeviceTwinNextConfigNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this edge diagnostics get device twin next config not found response has a 4xx status code
func (o *EdgeDiagnosticsGetDeviceTwinNextConfigNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this edge diagnostics get device twin next config not found response has a 5xx status code
func (o *EdgeDiagnosticsGetDeviceTwinNextConfigNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this edge diagnostics get device twin next config not found response a status code equal to that given
func (o *EdgeDiagnosticsGetDeviceTwinNextConfigNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the edge diagnostics get device twin next config not found response
func (o *EdgeDiagnosticsGetDeviceTwinNextConfigNotFound) Code() int {
	return 404
}

func (o *EdgeDiagnosticsGetDeviceTwinNextConfigNotFound) Error() string {
	return fmt.Sprintf("[GET /v1/devices/id/{id}/config/next][%d] edgeDiagnosticsGetDeviceTwinNextConfigNotFound  %+v", 404, o.Payload)
}

func (o *EdgeDiagnosticsGetDeviceTwinNextConfigNotFound) String() string {
	return fmt.Sprintf("[GET /v1/devices/id/{id}/config/next][%d] edgeDiagnosticsGetDeviceTwinNextConfigNotFound  %+v", 404, o.Payload)
}

func (o *EdgeDiagnosticsGetDeviceTwinNextConfigNotFound) GetPayload() *swagger_models.ZsrvResponse {
	return o.Payload
}

func (o *EdgeDiagnosticsGetDeviceTwinNextConfigNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(swagger_models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEdgeDiagnosticsGetDeviceTwinNextConfigInternalServerError creates a EdgeDiagnosticsGetDeviceTwinNextConfigInternalServerError with default headers values
func NewEdgeDiagnosticsGetDeviceTwinNextConfigInternalServerError() *EdgeDiagnosticsGetDeviceTwinNextConfigInternalServerError {
	return &EdgeDiagnosticsGetDeviceTwinNextConfigInternalServerError{}
}

/*
EdgeDiagnosticsGetDeviceTwinNextConfigInternalServerError describes a response with status code 500, with default header values.

Internal Server Error. The API gateway experienced an unexpected condition. Specific error condition is indicated in error codes.
*/
type EdgeDiagnosticsGetDeviceTwinNextConfigInternalServerError struct {
	Payload *swagger_models.ZsrvResponse
}

// IsSuccess returns true when this edge diagnostics get device twin next config internal server error response has a 2xx status code
func (o *EdgeDiagnosticsGetDeviceTwinNextConfigInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this edge diagnostics get device twin next config internal server error response has a 3xx status code
func (o *EdgeDiagnosticsGetDeviceTwinNextConfigInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this edge diagnostics get device twin next config internal server error response has a 4xx status code
func (o *EdgeDiagnosticsGetDeviceTwinNextConfigInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this edge diagnostics get device twin next config internal server error response has a 5xx status code
func (o *EdgeDiagnosticsGetDeviceTwinNextConfigInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this edge diagnostics get device twin next config internal server error response a status code equal to that given
func (o *EdgeDiagnosticsGetDeviceTwinNextConfigInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the edge diagnostics get device twin next config internal server error response
func (o *EdgeDiagnosticsGetDeviceTwinNextConfigInternalServerError) Code() int {
	return 500
}

func (o *EdgeDiagnosticsGetDeviceTwinNextConfigInternalServerError) Error() string {
	return fmt.Sprintf("[GET /v1/devices/id/{id}/config/next][%d] edgeDiagnosticsGetDeviceTwinNextConfigInternalServerError  %+v", 500, o.Payload)
}

func (o *EdgeDiagnosticsGetDeviceTwinNextConfigInternalServerError) String() string {
	return fmt.Sprintf("[GET /v1/devices/id/{id}/config/next][%d] edgeDiagnosticsGetDeviceTwinNextConfigInternalServerError  %+v", 500, o.Payload)
}

func (o *EdgeDiagnosticsGetDeviceTwinNextConfigInternalServerError) GetPayload() *swagger_models.ZsrvResponse {
	return o.Payload
}

func (o *EdgeDiagnosticsGetDeviceTwinNextConfigInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(swagger_models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEdgeDiagnosticsGetDeviceTwinNextConfigGatewayTimeout creates a EdgeDiagnosticsGetDeviceTwinNextConfigGatewayTimeout with default headers values
func NewEdgeDiagnosticsGetDeviceTwinNextConfigGatewayTimeout() *EdgeDiagnosticsGetDeviceTwinNextConfigGatewayTimeout {
	return &EdgeDiagnosticsGetDeviceTwinNextConfigGatewayTimeout{}
}

/*
EdgeDiagnosticsGetDeviceTwinNextConfigGatewayTimeout describes a response with status code 504, with default header values.

Gateway Timeout. The API gateway did not receive a timely response from an upstream microservice it needed to communicate with in order to complete the request.
*/
type EdgeDiagnosticsGetDeviceTwinNextConfigGatewayTimeout struct {
	Payload *swagger_models.ZsrvResponse
}

// IsSuccess returns true when this edge diagnostics get device twin next config gateway timeout response has a 2xx status code
func (o *EdgeDiagnosticsGetDeviceTwinNextConfigGatewayTimeout) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this edge diagnostics get device twin next config gateway timeout response has a 3xx status code
func (o *EdgeDiagnosticsGetDeviceTwinNextConfigGatewayTimeout) IsRedirect() bool {
	return false
}

// IsClientError returns true when this edge diagnostics get device twin next config gateway timeout response has a 4xx status code
func (o *EdgeDiagnosticsGetDeviceTwinNextConfigGatewayTimeout) IsClientError() bool {
	return false
}

// IsServerError returns true when this edge diagnostics get device twin next config gateway timeout response has a 5xx status code
func (o *EdgeDiagnosticsGetDeviceTwinNextConfigGatewayTimeout) IsServerError() bool {
	return true
}

// IsCode returns true when this edge diagnostics get device twin next config gateway timeout response a status code equal to that given
func (o *EdgeDiagnosticsGetDeviceTwinNextConfigGatewayTimeout) IsCode(code int) bool {
	return code == 504
}

// Code gets the status code for the edge diagnostics get device twin next config gateway timeout response
func (o *EdgeDiagnosticsGetDeviceTwinNextConfigGatewayTimeout) Code() int {
	return 504
}

func (o *EdgeDiagnosticsGetDeviceTwinNextConfigGatewayTimeout) Error() string {
	return fmt.Sprintf("[GET /v1/devices/id/{id}/config/next][%d] edgeDiagnosticsGetDeviceTwinNextConfigGatewayTimeout  %+v", 504, o.Payload)
}

func (o *EdgeDiagnosticsGetDeviceTwinNextConfigGatewayTimeout) String() string {
	return fmt.Sprintf("[GET /v1/devices/id/{id}/config/next][%d] edgeDiagnosticsGetDeviceTwinNextConfigGatewayTimeout  %+v", 504, o.Payload)
}

func (o *EdgeDiagnosticsGetDeviceTwinNextConfigGatewayTimeout) GetPayload() *swagger_models.ZsrvResponse {
	return o.Payload
}

func (o *EdgeDiagnosticsGetDeviceTwinNextConfigGatewayTimeout) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(swagger_models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEdgeDiagnosticsGetDeviceTwinNextConfigDefault creates a EdgeDiagnosticsGetDeviceTwinNextConfigDefault with default headers values
func NewEdgeDiagnosticsGetDeviceTwinNextConfigDefault(code int) *EdgeDiagnosticsGetDeviceTwinNextConfigDefault {
	return &EdgeDiagnosticsGetDeviceTwinNextConfigDefault{
		_statusCode: code,
	}
}

/*
EdgeDiagnosticsGetDeviceTwinNextConfigDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type EdgeDiagnosticsGetDeviceTwinNextConfigDefault struct {
	_statusCode int

	Payload *swagger_models.GooglerpcStatus
}

// IsSuccess returns true when this edge diagnostics get device twin next config default response has a 2xx status code
func (o *EdgeDiagnosticsGetDeviceTwinNextConfigDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this edge diagnostics get device twin next config default response has a 3xx status code
func (o *EdgeDiagnosticsGetDeviceTwinNextConfigDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this edge diagnostics get device twin next config default response has a 4xx status code
func (o *EdgeDiagnosticsGetDeviceTwinNextConfigDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this edge diagnostics get device twin next config default response has a 5xx status code
func (o *EdgeDiagnosticsGetDeviceTwinNextConfigDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this edge diagnostics get device twin next config default response a status code equal to that given
func (o *EdgeDiagnosticsGetDeviceTwinNextConfigDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the edge diagnostics get device twin next config default response
func (o *EdgeDiagnosticsGetDeviceTwinNextConfigDefault) Code() int {
	return o._statusCode
}

func (o *EdgeDiagnosticsGetDeviceTwinNextConfigDefault) Error() string {
	return fmt.Sprintf("[GET /v1/devices/id/{id}/config/next][%d] EdgeDiagnostics_GetDeviceTwinNextConfig default  %+v", o._statusCode, o.Payload)
}

func (o *EdgeDiagnosticsGetDeviceTwinNextConfigDefault) String() string {
	return fmt.Sprintf("[GET /v1/devices/id/{id}/config/next][%d] EdgeDiagnostics_GetDeviceTwinNextConfig default  %+v", o._statusCode, o.Payload)
}

func (o *EdgeDiagnosticsGetDeviceTwinNextConfigDefault) GetPayload() *swagger_models.GooglerpcStatus {
	return o.Payload
}

func (o *EdgeDiagnosticsGetDeviceTwinNextConfigDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(swagger_models.GooglerpcStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
