// Copyright (c) 2018-2021 Zededa, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by go-swagger; DO NOT EDIT.

package identity_access_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/zededa/zedcloud-api/swagger_models"
)

// NewCreateEnterpriseParams creates a new CreateEnterpriseParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateEnterpriseParams() *CreateEnterpriseParams {
	return &CreateEnterpriseParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateEnterpriseParamsWithTimeout creates a new CreateEnterpriseParams object
// with the ability to set a timeout on a request.
func NewCreateEnterpriseParamsWithTimeout(timeout time.Duration) *CreateEnterpriseParams {
	return &CreateEnterpriseParams{
		timeout: timeout,
	}
}

// NewCreateEnterpriseParamsWithContext creates a new CreateEnterpriseParams object
// with the ability to set a context for a request.
func NewCreateEnterpriseParamsWithContext(ctx context.Context) *CreateEnterpriseParams {
	return &CreateEnterpriseParams{
		Context: ctx,
	}
}

// NewCreateEnterpriseParamsWithHTTPClient creates a new CreateEnterpriseParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateEnterpriseParamsWithHTTPClient(client *http.Client) *CreateEnterpriseParams {
	return &CreateEnterpriseParams{
		HTTPClient: client,
	}
}

/* CreateEnterpriseParams contains all the parameters to send to the API endpoint
   for the create enterprise operation.

   Typically these are written to a http.Request.
*/
type CreateEnterpriseParams struct {

	/* XRequestID.

	   User-Agent specified id to track a request
	*/
	XRequestID *string

	// Body.
	Body *swagger_models.Enterprise

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create enterprise params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateEnterpriseParams) WithDefaults() *CreateEnterpriseParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create enterprise params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateEnterpriseParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create enterprise params
func (o *CreateEnterpriseParams) WithTimeout(timeout time.Duration) *CreateEnterpriseParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create enterprise params
func (o *CreateEnterpriseParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create enterprise params
func (o *CreateEnterpriseParams) WithContext(ctx context.Context) *CreateEnterpriseParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create enterprise params
func (o *CreateEnterpriseParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create enterprise params
func (o *CreateEnterpriseParams) WithHTTPClient(client *http.Client) *CreateEnterpriseParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create enterprise params
func (o *CreateEnterpriseParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXRequestID adds the xRequestID to the create enterprise params
func (o *CreateEnterpriseParams) WithXRequestID(xRequestID *string) *CreateEnterpriseParams {
	o.SetXRequestID(xRequestID)
	return o
}

// SetXRequestID adds the xRequestId to the create enterprise params
func (o *CreateEnterpriseParams) SetXRequestID(xRequestID *string) {
	o.XRequestID = xRequestID
}

// WithBody adds the body to the create enterprise params
func (o *CreateEnterpriseParams) WithBody(body *swagger_models.Enterprise) *CreateEnterpriseParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create enterprise params
func (o *CreateEnterpriseParams) SetBody(body *swagger_models.Enterprise) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateEnterpriseParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XRequestID != nil {

		// header param X-Request-Id
		if err := r.SetHeaderParam("X-Request-Id", *o.XRequestID); err != nil {
			return err
		}
	}
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
