// Copyright (c) 2018-2021 Zededa, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by go-swagger; DO NOT EDIT.

package identity_access_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetUserSelfParams creates a new GetUserSelfParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetUserSelfParams() *GetUserSelfParams {
	return &GetUserSelfParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetUserSelfParamsWithTimeout creates a new GetUserSelfParams object
// with the ability to set a timeout on a request.
func NewGetUserSelfParamsWithTimeout(timeout time.Duration) *GetUserSelfParams {
	return &GetUserSelfParams{
		timeout: timeout,
	}
}

// NewGetUserSelfParamsWithContext creates a new GetUserSelfParams object
// with the ability to set a context for a request.
func NewGetUserSelfParamsWithContext(ctx context.Context) *GetUserSelfParams {
	return &GetUserSelfParams{
		Context: ctx,
	}
}

// NewGetUserSelfParamsWithHTTPClient creates a new GetUserSelfParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetUserSelfParamsWithHTTPClient(client *http.Client) *GetUserSelfParams {
	return &GetUserSelfParams{
		HTTPClient: client,
	}
}

/* GetUserSelfParams contains all the parameters to send to the API endpoint
   for the get user self operation.

   Typically these are written to a http.Request.
*/
type GetUserSelfParams struct {

	/* XRequestID.

	   User-Agent specified id to track a request
	*/
	XRequestID *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get user self params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetUserSelfParams) WithDefaults() *GetUserSelfParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get user self params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetUserSelfParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get user self params
func (o *GetUserSelfParams) WithTimeout(timeout time.Duration) *GetUserSelfParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get user self params
func (o *GetUserSelfParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get user self params
func (o *GetUserSelfParams) WithContext(ctx context.Context) *GetUserSelfParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get user self params
func (o *GetUserSelfParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get user self params
func (o *GetUserSelfParams) WithHTTPClient(client *http.Client) *GetUserSelfParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get user self params
func (o *GetUserSelfParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXRequestID adds the xRequestID to the get user self params
func (o *GetUserSelfParams) WithXRequestID(xRequestID *string) *GetUserSelfParams {
	o.SetXRequestID(xRequestID)
	return o
}

// SetXRequestID adds the xRequestId to the get user self params
func (o *GetUserSelfParams) SetXRequestID(xRequestID *string) {
	o.XRequestID = xRequestID
}

// WriteToRequest writes these params to a swagger request
func (o *GetUserSelfParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XRequestID != nil {

		// header param X-Request-Id
		if err := r.SetHeaderParam("X-Request-Id", *o.XRequestID); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
