// Copyright (c) 2018-2021 Zededa, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by go-swagger; DO NOT EDIT.

package identity_access_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/zededa/zedcloud-api/swagger_models"
)

// IdentityAccessManagementGetEnterpriseReader is a Reader for the IdentityAccessManagementGetEnterprise structure.
type IdentityAccessManagementGetEnterpriseReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IdentityAccessManagementGetEnterpriseReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewIdentityAccessManagementGetEnterpriseOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewIdentityAccessManagementGetEnterpriseUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewIdentityAccessManagementGetEnterpriseForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewIdentityAccessManagementGetEnterpriseNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewIdentityAccessManagementGetEnterpriseInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 504:
		result := NewIdentityAccessManagementGetEnterpriseGatewayTimeout()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewIdentityAccessManagementGetEnterpriseDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewIdentityAccessManagementGetEnterpriseOK creates a IdentityAccessManagementGetEnterpriseOK with default headers values
func NewIdentityAccessManagementGetEnterpriseOK() *IdentityAccessManagementGetEnterpriseOK {
	return &IdentityAccessManagementGetEnterpriseOK{}
}

/* IdentityAccessManagementGetEnterpriseOK describes a response with status code 200, with default header values.

A successful response.
*/
type IdentityAccessManagementGetEnterpriseOK struct {
	Payload *swagger_models.CrudResponseRead
}

func (o *IdentityAccessManagementGetEnterpriseOK) Error() string {
	return fmt.Sprintf("[GET /v1/enterprises/id/{id}][%d] identityAccessManagementGetEnterpriseOK  %+v", 200, o.Payload)
}
func (o *IdentityAccessManagementGetEnterpriseOK) GetPayload() *swagger_models.CrudResponseRead {
	return o.Payload
}

func (o *IdentityAccessManagementGetEnterpriseOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(swagger_models.CrudResponseRead)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewIdentityAccessManagementGetEnterpriseUnauthorized creates a IdentityAccessManagementGetEnterpriseUnauthorized with default headers values
func NewIdentityAccessManagementGetEnterpriseUnauthorized() *IdentityAccessManagementGetEnterpriseUnauthorized {
	return &IdentityAccessManagementGetEnterpriseUnauthorized{}
}

/* IdentityAccessManagementGetEnterpriseUnauthorized describes a response with status code 401, with default header values.

Unauthorized. The API gateway did not process the request because it lacks valid authentication credentials for the target resource. The request header has either no authorization details or an authorization that has been refused.
*/
type IdentityAccessManagementGetEnterpriseUnauthorized struct {
	Payload *swagger_models.ZsrvResponse
}

func (o *IdentityAccessManagementGetEnterpriseUnauthorized) Error() string {
	return fmt.Sprintf("[GET /v1/enterprises/id/{id}][%d] identityAccessManagementGetEnterpriseUnauthorized  %+v", 401, o.Payload)
}
func (o *IdentityAccessManagementGetEnterpriseUnauthorized) GetPayload() *swagger_models.ZsrvResponse {
	return o.Payload
}

func (o *IdentityAccessManagementGetEnterpriseUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(swagger_models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewIdentityAccessManagementGetEnterpriseForbidden creates a IdentityAccessManagementGetEnterpriseForbidden with default headers values
func NewIdentityAccessManagementGetEnterpriseForbidden() *IdentityAccessManagementGetEnterpriseForbidden {
	return &IdentityAccessManagementGetEnterpriseForbidden{}
}

/* IdentityAccessManagementGetEnterpriseForbidden describes a response with status code 403, with default header values.

Forbidden. The API gateway did not process the request because the requestor does not have edge-node level access permission for the operation or does not have access scope to the project.
*/
type IdentityAccessManagementGetEnterpriseForbidden struct {
	Payload *swagger_models.ZsrvResponse
}

func (o *IdentityAccessManagementGetEnterpriseForbidden) Error() string {
	return fmt.Sprintf("[GET /v1/enterprises/id/{id}][%d] identityAccessManagementGetEnterpriseForbidden  %+v", 403, o.Payload)
}
func (o *IdentityAccessManagementGetEnterpriseForbidden) GetPayload() *swagger_models.ZsrvResponse {
	return o.Payload
}

func (o *IdentityAccessManagementGetEnterpriseForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(swagger_models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewIdentityAccessManagementGetEnterpriseNotFound creates a IdentityAccessManagementGetEnterpriseNotFound with default headers values
func NewIdentityAccessManagementGetEnterpriseNotFound() *IdentityAccessManagementGetEnterpriseNotFound {
	return &IdentityAccessManagementGetEnterpriseNotFound{}
}

/* IdentityAccessManagementGetEnterpriseNotFound describes a response with status code 404, with default header values.

Not Found. The API gateway did not process the request because the requested resource could not be found.
*/
type IdentityAccessManagementGetEnterpriseNotFound struct {
	Payload *swagger_models.ZsrvResponse
}

func (o *IdentityAccessManagementGetEnterpriseNotFound) Error() string {
	return fmt.Sprintf("[GET /v1/enterprises/id/{id}][%d] identityAccessManagementGetEnterpriseNotFound  %+v", 404, o.Payload)
}
func (o *IdentityAccessManagementGetEnterpriseNotFound) GetPayload() *swagger_models.ZsrvResponse {
	return o.Payload
}

func (o *IdentityAccessManagementGetEnterpriseNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(swagger_models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewIdentityAccessManagementGetEnterpriseInternalServerError creates a IdentityAccessManagementGetEnterpriseInternalServerError with default headers values
func NewIdentityAccessManagementGetEnterpriseInternalServerError() *IdentityAccessManagementGetEnterpriseInternalServerError {
	return &IdentityAccessManagementGetEnterpriseInternalServerError{}
}

/* IdentityAccessManagementGetEnterpriseInternalServerError describes a response with status code 500, with default header values.

Internal Server Error. The API gateway experienced an unexpected condition. Specific error condition is indicated in error codes.
*/
type IdentityAccessManagementGetEnterpriseInternalServerError struct {
	Payload *swagger_models.ZsrvResponse
}

func (o *IdentityAccessManagementGetEnterpriseInternalServerError) Error() string {
	return fmt.Sprintf("[GET /v1/enterprises/id/{id}][%d] identityAccessManagementGetEnterpriseInternalServerError  %+v", 500, o.Payload)
}
func (o *IdentityAccessManagementGetEnterpriseInternalServerError) GetPayload() *swagger_models.ZsrvResponse {
	return o.Payload
}

func (o *IdentityAccessManagementGetEnterpriseInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(swagger_models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewIdentityAccessManagementGetEnterpriseGatewayTimeout creates a IdentityAccessManagementGetEnterpriseGatewayTimeout with default headers values
func NewIdentityAccessManagementGetEnterpriseGatewayTimeout() *IdentityAccessManagementGetEnterpriseGatewayTimeout {
	return &IdentityAccessManagementGetEnterpriseGatewayTimeout{}
}

/* IdentityAccessManagementGetEnterpriseGatewayTimeout describes a response with status code 504, with default header values.

Gateway Timeout. The API gateway did not receive a timely response from an upstream microservice it needed to communicate with in order to complete the request.
*/
type IdentityAccessManagementGetEnterpriseGatewayTimeout struct {
	Payload *swagger_models.ZsrvResponse
}

func (o *IdentityAccessManagementGetEnterpriseGatewayTimeout) Error() string {
	return fmt.Sprintf("[GET /v1/enterprises/id/{id}][%d] identityAccessManagementGetEnterpriseGatewayTimeout  %+v", 504, o.Payload)
}
func (o *IdentityAccessManagementGetEnterpriseGatewayTimeout) GetPayload() *swagger_models.ZsrvResponse {
	return o.Payload
}

func (o *IdentityAccessManagementGetEnterpriseGatewayTimeout) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(swagger_models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewIdentityAccessManagementGetEnterpriseDefault creates a IdentityAccessManagementGetEnterpriseDefault with default headers values
func NewIdentityAccessManagementGetEnterpriseDefault(code int) *IdentityAccessManagementGetEnterpriseDefault {
	return &IdentityAccessManagementGetEnterpriseDefault{
		_statusCode: code,
	}
}

/* IdentityAccessManagementGetEnterpriseDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type IdentityAccessManagementGetEnterpriseDefault struct {
	_statusCode int

	Payload *swagger_models.GooglerpcStatus
}

// Code gets the status code for the identity access management get enterprise default response
func (o *IdentityAccessManagementGetEnterpriseDefault) Code() int {
	return o._statusCode
}

func (o *IdentityAccessManagementGetEnterpriseDefault) Error() string {
	return fmt.Sprintf("[GET /v1/enterprises/id/{id}][%d] IdentityAccessManagement_GetEnterprise default  %+v", o._statusCode, o.Payload)
}
func (o *IdentityAccessManagementGetEnterpriseDefault) GetPayload() *swagger_models.GooglerpcStatus {
	return o.Payload
}

func (o *IdentityAccessManagementGetEnterpriseDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(swagger_models.GooglerpcStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
