// Copyright (c) 2018-2021 Zededa, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by go-swagger; DO NOT EDIT.

package identity_access_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewQueryUserSessionsParams creates a new QueryUserSessionsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewQueryUserSessionsParams() *QueryUserSessionsParams {
	return &QueryUserSessionsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewQueryUserSessionsParamsWithTimeout creates a new QueryUserSessionsParams object
// with the ability to set a timeout on a request.
func NewQueryUserSessionsParamsWithTimeout(timeout time.Duration) *QueryUserSessionsParams {
	return &QueryUserSessionsParams{
		timeout: timeout,
	}
}

// NewQueryUserSessionsParamsWithContext creates a new QueryUserSessionsParams object
// with the ability to set a context for a request.
func NewQueryUserSessionsParamsWithContext(ctx context.Context) *QueryUserSessionsParams {
	return &QueryUserSessionsParams{
		Context: ctx,
	}
}

// NewQueryUserSessionsParamsWithHTTPClient creates a new QueryUserSessionsParams object
// with the ability to set a custom HTTPClient for a request.
func NewQueryUserSessionsParamsWithHTTPClient(client *http.Client) *QueryUserSessionsParams {
	return &QueryUserSessionsParams{
		HTTPClient: client,
	}
}

/* QueryUserSessionsParams contains all the parameters to send to the API endpoint
   for the query user sessions operation.

   Typically these are written to a http.Request.
*/
type QueryUserSessionsParams struct {

	/* XRequestID.

	   User-Agent specified id to track a request
	*/
	XRequestID *string

	// TokenBase64.
	TokenBase64 *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the query user sessions params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *QueryUserSessionsParams) WithDefaults() *QueryUserSessionsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the query user sessions params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *QueryUserSessionsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the query user sessions params
func (o *QueryUserSessionsParams) WithTimeout(timeout time.Duration) *QueryUserSessionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the query user sessions params
func (o *QueryUserSessionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the query user sessions params
func (o *QueryUserSessionsParams) WithContext(ctx context.Context) *QueryUserSessionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the query user sessions params
func (o *QueryUserSessionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the query user sessions params
func (o *QueryUserSessionsParams) WithHTTPClient(client *http.Client) *QueryUserSessionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the query user sessions params
func (o *QueryUserSessionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXRequestID adds the xRequestID to the query user sessions params
func (o *QueryUserSessionsParams) WithXRequestID(xRequestID *string) *QueryUserSessionsParams {
	o.SetXRequestID(xRequestID)
	return o
}

// SetXRequestID adds the xRequestId to the query user sessions params
func (o *QueryUserSessionsParams) SetXRequestID(xRequestID *string) {
	o.XRequestID = xRequestID
}

// WithTokenBase64 adds the tokenBase64 to the query user sessions params
func (o *QueryUserSessionsParams) WithTokenBase64(tokenBase64 *string) *QueryUserSessionsParams {
	o.SetTokenBase64(tokenBase64)
	return o
}

// SetTokenBase64 adds the tokenBase64 to the query user sessions params
func (o *QueryUserSessionsParams) SetTokenBase64(tokenBase64 *string) {
	o.TokenBase64 = tokenBase64
}

// WriteToRequest writes these params to a swagger request
func (o *QueryUserSessionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XRequestID != nil {

		// header param X-Request-Id
		if err := r.SetHeaderParam("X-Request-Id", *o.XRequestID); err != nil {
			return err
		}
	}

	if o.TokenBase64 != nil {

		// query param token.base64
		var qrTokenBase64 string

		if o.TokenBase64 != nil {
			qrTokenBase64 = *o.TokenBase64
		}
		qTokenBase64 := qrTokenBase64
		if qTokenBase64 != "" {

			if err := r.SetQueryParam("token.base64", qTokenBase64); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
