// Copyright (c) 2018-2021 Zededa, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by go-swagger; DO NOT EDIT.

package datastore_configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/zededa/zedcloud-api/swagger_models"
)

// NewCreateDatastoreParams creates a new CreateDatastoreParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateDatastoreParams() *CreateDatastoreParams {
	return &CreateDatastoreParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateDatastoreParamsWithTimeout creates a new CreateDatastoreParams object
// with the ability to set a timeout on a request.
func NewCreateDatastoreParamsWithTimeout(timeout time.Duration) *CreateDatastoreParams {
	return &CreateDatastoreParams{
		timeout: timeout,
	}
}

// NewCreateDatastoreParamsWithContext creates a new CreateDatastoreParams object
// with the ability to set a context for a request.
func NewCreateDatastoreParamsWithContext(ctx context.Context) *CreateDatastoreParams {
	return &CreateDatastoreParams{
		Context: ctx,
	}
}

// NewCreateDatastoreParamsWithHTTPClient creates a new CreateDatastoreParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateDatastoreParamsWithHTTPClient(client *http.Client) *CreateDatastoreParams {
	return &CreateDatastoreParams{
		HTTPClient: client,
	}
}

/* CreateDatastoreParams contains all the parameters to send to the API endpoint
   for the create datastore operation.

   Typically these are written to a http.Request.
*/
type CreateDatastoreParams struct {

	/* XRequestID.

	   User-Agent specified id to track a request
	*/
	XRequestID *string

	// Body.
	Body *swagger_models.DatastoreInfo

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create datastore params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateDatastoreParams) WithDefaults() *CreateDatastoreParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create datastore params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateDatastoreParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create datastore params
func (o *CreateDatastoreParams) WithTimeout(timeout time.Duration) *CreateDatastoreParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create datastore params
func (o *CreateDatastoreParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create datastore params
func (o *CreateDatastoreParams) WithContext(ctx context.Context) *CreateDatastoreParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create datastore params
func (o *CreateDatastoreParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create datastore params
func (o *CreateDatastoreParams) WithHTTPClient(client *http.Client) *CreateDatastoreParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create datastore params
func (o *CreateDatastoreParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXRequestID adds the xRequestID to the create datastore params
func (o *CreateDatastoreParams) WithXRequestID(xRequestID *string) *CreateDatastoreParams {
	o.SetXRequestID(xRequestID)
	return o
}

// SetXRequestID adds the xRequestId to the create datastore params
func (o *CreateDatastoreParams) SetXRequestID(xRequestID *string) {
	o.XRequestID = xRequestID
}

// WithBody adds the body to the create datastore params
func (o *CreateDatastoreParams) WithBody(body *swagger_models.DatastoreInfo) *CreateDatastoreParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create datastore params
func (o *CreateDatastoreParams) SetBody(body *swagger_models.DatastoreInfo) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateDatastoreParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XRequestID != nil {

		// header param X-Request-Id
		if err := r.SetHeaderParam("X-Request-Id", *o.XRequestID); err != nil {
			return err
		}
	}
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
