// Copyright (c) 2018-2021 Zededa, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by go-swagger; DO NOT EDIT.

package bulk_job_ops

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/zededa/zedcloud-api/swagger_models"
)

// BulkImportHardwareModelsReader is a Reader for the BulkImportHardwareModels structure.
type BulkImportHardwareModelsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *BulkImportHardwareModelsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewBulkImportHardwareModelsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewBulkImportHardwareModelsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewBulkImportHardwareModelsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewBulkImportHardwareModelsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewBulkImportHardwareModelsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewBulkImportHardwareModelsConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewBulkImportHardwareModelsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 504:
		result := NewBulkImportHardwareModelsGatewayTimeout()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewBulkImportHardwareModelsOK creates a BulkImportHardwareModelsOK with default headers values
func NewBulkImportHardwareModelsOK() *BulkImportHardwareModelsOK {
	return &BulkImportHardwareModelsOK{}
}

/* BulkImportHardwareModelsOK describes a response with status code 200, with default header values.

A successful response.
*/
type BulkImportHardwareModelsOK struct {
	Payload *swagger_models.ZsrvResponse
}

func (o *BulkImportHardwareModelsOK) Error() string {
	return fmt.Sprintf("[PUT /v1/jobs/models/import][%d] bulkImportHardwareModelsOK  %+v", 200, o.Payload)
}
func (o *BulkImportHardwareModelsOK) GetPayload() *swagger_models.ZsrvResponse {
	return o.Payload
}

func (o *BulkImportHardwareModelsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(swagger_models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewBulkImportHardwareModelsBadRequest creates a BulkImportHardwareModelsBadRequest with default headers values
func NewBulkImportHardwareModelsBadRequest() *BulkImportHardwareModelsBadRequest {
	return &BulkImportHardwareModelsBadRequest{}
}

/* BulkImportHardwareModelsBadRequest describes a response with status code 400, with default header values.

Bad Request. The API gateway did not process the request because of missing parameter or invalid value of parameters.
*/
type BulkImportHardwareModelsBadRequest struct {
	Payload *swagger_models.ZsrvResponse
}

func (o *BulkImportHardwareModelsBadRequest) Error() string {
	return fmt.Sprintf("[PUT /v1/jobs/models/import][%d] bulkImportHardwareModelsBadRequest  %+v", 400, o.Payload)
}
func (o *BulkImportHardwareModelsBadRequest) GetPayload() *swagger_models.ZsrvResponse {
	return o.Payload
}

func (o *BulkImportHardwareModelsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(swagger_models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewBulkImportHardwareModelsUnauthorized creates a BulkImportHardwareModelsUnauthorized with default headers values
func NewBulkImportHardwareModelsUnauthorized() *BulkImportHardwareModelsUnauthorized {
	return &BulkImportHardwareModelsUnauthorized{}
}

/* BulkImportHardwareModelsUnauthorized describes a response with status code 401, with default header values.

Unauthorized. The API gateway did not process the request because it lacks valid authentication credentials for the target resource. The request header has either no authorization details or an authorization that has been refused.
*/
type BulkImportHardwareModelsUnauthorized struct {
	Payload *swagger_models.ZsrvResponse
}

func (o *BulkImportHardwareModelsUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /v1/jobs/models/import][%d] bulkImportHardwareModelsUnauthorized  %+v", 401, o.Payload)
}
func (o *BulkImportHardwareModelsUnauthorized) GetPayload() *swagger_models.ZsrvResponse {
	return o.Payload
}

func (o *BulkImportHardwareModelsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(swagger_models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewBulkImportHardwareModelsForbidden creates a BulkImportHardwareModelsForbidden with default headers values
func NewBulkImportHardwareModelsForbidden() *BulkImportHardwareModelsForbidden {
	return &BulkImportHardwareModelsForbidden{}
}

/* BulkImportHardwareModelsForbidden describes a response with status code 403, with default header values.

Forbidden. The API gateway did not process the request because the requestor does not have edge-app level access permission for the operation or does not have access scope to the project.
*/
type BulkImportHardwareModelsForbidden struct {
	Payload *swagger_models.ZsrvResponse
}

func (o *BulkImportHardwareModelsForbidden) Error() string {
	return fmt.Sprintf("[PUT /v1/jobs/models/import][%d] bulkImportHardwareModelsForbidden  %+v", 403, o.Payload)
}
func (o *BulkImportHardwareModelsForbidden) GetPayload() *swagger_models.ZsrvResponse {
	return o.Payload
}

func (o *BulkImportHardwareModelsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(swagger_models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewBulkImportHardwareModelsNotFound creates a BulkImportHardwareModelsNotFound with default headers values
func NewBulkImportHardwareModelsNotFound() *BulkImportHardwareModelsNotFound {
	return &BulkImportHardwareModelsNotFound{}
}

/* BulkImportHardwareModelsNotFound describes a response with status code 404, with default header values.

Not Found. The API gateway did not process the request because the requested resource could not be found.
*/
type BulkImportHardwareModelsNotFound struct {
	Payload *swagger_models.ZsrvResponse
}

func (o *BulkImportHardwareModelsNotFound) Error() string {
	return fmt.Sprintf("[PUT /v1/jobs/models/import][%d] bulkImportHardwareModelsNotFound  %+v", 404, o.Payload)
}
func (o *BulkImportHardwareModelsNotFound) GetPayload() *swagger_models.ZsrvResponse {
	return o.Payload
}

func (o *BulkImportHardwareModelsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(swagger_models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewBulkImportHardwareModelsConflict creates a BulkImportHardwareModelsConflict with default headers values
func NewBulkImportHardwareModelsConflict() *BulkImportHardwareModelsConflict {
	return &BulkImportHardwareModelsConflict{}
}

/* BulkImportHardwareModelsConflict describes a response with status code 409, with default header values.

Conflict. The API gateway did not process the request because this operation will conflict with an already existing asynchronous job request record.
*/
type BulkImportHardwareModelsConflict struct {
	Payload *swagger_models.ZsrvResponse
}

func (o *BulkImportHardwareModelsConflict) Error() string {
	return fmt.Sprintf("[PUT /v1/jobs/models/import][%d] bulkImportHardwareModelsConflict  %+v", 409, o.Payload)
}
func (o *BulkImportHardwareModelsConflict) GetPayload() *swagger_models.ZsrvResponse {
	return o.Payload
}

func (o *BulkImportHardwareModelsConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(swagger_models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewBulkImportHardwareModelsInternalServerError creates a BulkImportHardwareModelsInternalServerError with default headers values
func NewBulkImportHardwareModelsInternalServerError() *BulkImportHardwareModelsInternalServerError {
	return &BulkImportHardwareModelsInternalServerError{}
}

/* BulkImportHardwareModelsInternalServerError describes a response with status code 500, with default header values.

Internal Server Error. The API gateway experienced an unexpected condition. Specific error condition is indicated in error codes.
*/
type BulkImportHardwareModelsInternalServerError struct {
	Payload *swagger_models.ZsrvResponse
}

func (o *BulkImportHardwareModelsInternalServerError) Error() string {
	return fmt.Sprintf("[PUT /v1/jobs/models/import][%d] bulkImportHardwareModelsInternalServerError  %+v", 500, o.Payload)
}
func (o *BulkImportHardwareModelsInternalServerError) GetPayload() *swagger_models.ZsrvResponse {
	return o.Payload
}

func (o *BulkImportHardwareModelsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(swagger_models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewBulkImportHardwareModelsGatewayTimeout creates a BulkImportHardwareModelsGatewayTimeout with default headers values
func NewBulkImportHardwareModelsGatewayTimeout() *BulkImportHardwareModelsGatewayTimeout {
	return &BulkImportHardwareModelsGatewayTimeout{}
}

/* BulkImportHardwareModelsGatewayTimeout describes a response with status code 504, with default header values.

Gateway Timeout. The API gateway did not receive a timely response from an upstream microservice it needed to communicate with in order to complete the request.
*/
type BulkImportHardwareModelsGatewayTimeout struct {
	Payload *swagger_models.ZsrvResponse
}

func (o *BulkImportHardwareModelsGatewayTimeout) Error() string {
	return fmt.Sprintf("[PUT /v1/jobs/models/import][%d] bulkImportHardwareModelsGatewayTimeout  %+v", 504, o.Payload)
}
func (o *BulkImportHardwareModelsGatewayTimeout) GetPayload() *swagger_models.ZsrvResponse {
	return o.Payload
}

func (o *BulkImportHardwareModelsGatewayTimeout) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(swagger_models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
