// Copyright (c) 2018-2021 Zededa, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by go-swagger; DO NOT EDIT.

package cloud_diagnostics

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/zededa/zedcloud-api/swagger_models"
)

// CheckClusterHealth2Reader is a Reader for the CheckClusterHealth2 structure.
type CheckClusterHealth2Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CheckClusterHealth2Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCheckClusterHealth2OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewCheckClusterHealth2InternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 504:
		result := NewCheckClusterHealth2GatewayTimeout()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCheckClusterHealth2OK creates a CheckClusterHealth2OK with default headers values
func NewCheckClusterHealth2OK() *CheckClusterHealth2OK {
	return &CheckClusterHealth2OK{}
}

/* CheckClusterHealth2OK describes a response with status code 200, with default header values.

A successful response.
*/
type CheckClusterHealth2OK struct {
	Payload *swagger_models.PingMsgSendResp
}

func (o *CheckClusterHealth2OK) Error() string {
	return fmt.Sprintf("[GET /v1/cloud/ping/id/{pingId}][%d] checkClusterHealth2OK  %+v", 200, o.Payload)
}
func (o *CheckClusterHealth2OK) GetPayload() *swagger_models.PingMsgSendResp {
	return o.Payload
}

func (o *CheckClusterHealth2OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(swagger_models.PingMsgSendResp)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCheckClusterHealth2InternalServerError creates a CheckClusterHealth2InternalServerError with default headers values
func NewCheckClusterHealth2InternalServerError() *CheckClusterHealth2InternalServerError {
	return &CheckClusterHealth2InternalServerError{}
}

/* CheckClusterHealth2InternalServerError describes a response with status code 500, with default header values.

Internal Server Error. The API gateway experienced an unexpected condition. Specific error condition is indicated in error codes.
*/
type CheckClusterHealth2InternalServerError struct {
	Payload *swagger_models.ZsrvResponse
}

func (o *CheckClusterHealth2InternalServerError) Error() string {
	return fmt.Sprintf("[GET /v1/cloud/ping/id/{pingId}][%d] checkClusterHealth2InternalServerError  %+v", 500, o.Payload)
}
func (o *CheckClusterHealth2InternalServerError) GetPayload() *swagger_models.ZsrvResponse {
	return o.Payload
}

func (o *CheckClusterHealth2InternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(swagger_models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCheckClusterHealth2GatewayTimeout creates a CheckClusterHealth2GatewayTimeout with default headers values
func NewCheckClusterHealth2GatewayTimeout() *CheckClusterHealth2GatewayTimeout {
	return &CheckClusterHealth2GatewayTimeout{}
}

/* CheckClusterHealth2GatewayTimeout describes a response with status code 504, with default header values.

Gateway Timeout. The API gateway did not receive a timely response from an upstream microservice it needed to communicate with in order to complete the request.
*/
type CheckClusterHealth2GatewayTimeout struct {
	Payload *swagger_models.ZsrvResponse
}

func (o *CheckClusterHealth2GatewayTimeout) Error() string {
	return fmt.Sprintf("[GET /v1/cloud/ping/id/{pingId}][%d] checkClusterHealth2GatewayTimeout  %+v", 504, o.Payload)
}
func (o *CheckClusterHealth2GatewayTimeout) GetPayload() *swagger_models.ZsrvResponse {
	return o.Payload
}

func (o *CheckClusterHealth2GatewayTimeout) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(swagger_models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
