// Copyright (c) 2018-2021 Zededa, Inc.\n// SPDX-License-Identifier: Apache-2.0\n
// Code generated by go-swagger; DO NOT EDIT.

package cloud_diagnostics

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/zededa/zedcloud-api/swagger_models"
)

// CloudDiagnosticsMarkCloudPolicyLatestReader is a Reader for the CloudDiagnosticsMarkCloudPolicyLatest structure.
type CloudDiagnosticsMarkCloudPolicyLatestReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CloudDiagnosticsMarkCloudPolicyLatestReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCloudDiagnosticsMarkCloudPolicyLatestOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewCloudDiagnosticsMarkCloudPolicyLatestInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 504:
		result := NewCloudDiagnosticsMarkCloudPolicyLatestGatewayTimeout()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewCloudDiagnosticsMarkCloudPolicyLatestDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCloudDiagnosticsMarkCloudPolicyLatestOK creates a CloudDiagnosticsMarkCloudPolicyLatestOK with default headers values
func NewCloudDiagnosticsMarkCloudPolicyLatestOK() *CloudDiagnosticsMarkCloudPolicyLatestOK {
	return &CloudDiagnosticsMarkCloudPolicyLatestOK{}
}

/*
CloudDiagnosticsMarkCloudPolicyLatestOK describes a response with status code 200, with default header values.

A successful response.
*/
type CloudDiagnosticsMarkCloudPolicyLatestOK struct {
	Payload *swagger_models.PolicyDocVersionResp
}

// IsSuccess returns true when this cloud diagnostics mark cloud policy latest o k response has a 2xx status code
func (o *CloudDiagnosticsMarkCloudPolicyLatestOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this cloud diagnostics mark cloud policy latest o k response has a 3xx status code
func (o *CloudDiagnosticsMarkCloudPolicyLatestOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this cloud diagnostics mark cloud policy latest o k response has a 4xx status code
func (o *CloudDiagnosticsMarkCloudPolicyLatestOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this cloud diagnostics mark cloud policy latest o k response has a 5xx status code
func (o *CloudDiagnosticsMarkCloudPolicyLatestOK) IsServerError() bool {
	return false
}

// IsCode returns true when this cloud diagnostics mark cloud policy latest o k response a status code equal to that given
func (o *CloudDiagnosticsMarkCloudPolicyLatestOK) IsCode(code int) bool {
	return code == 200
}

func (o *CloudDiagnosticsMarkCloudPolicyLatestOK) Error() string {
	return fmt.Sprintf("[PUT /v1/cloud/policies][%d] cloudDiagnosticsMarkCloudPolicyLatestOK  %+v", 200, o.Payload)
}

func (o *CloudDiagnosticsMarkCloudPolicyLatestOK) String() string {
	return fmt.Sprintf("[PUT /v1/cloud/policies][%d] cloudDiagnosticsMarkCloudPolicyLatestOK  %+v", 200, o.Payload)
}

func (o *CloudDiagnosticsMarkCloudPolicyLatestOK) GetPayload() *swagger_models.PolicyDocVersionResp {
	return o.Payload
}

func (o *CloudDiagnosticsMarkCloudPolicyLatestOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(swagger_models.PolicyDocVersionResp)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCloudDiagnosticsMarkCloudPolicyLatestInternalServerError creates a CloudDiagnosticsMarkCloudPolicyLatestInternalServerError with default headers values
func NewCloudDiagnosticsMarkCloudPolicyLatestInternalServerError() *CloudDiagnosticsMarkCloudPolicyLatestInternalServerError {
	return &CloudDiagnosticsMarkCloudPolicyLatestInternalServerError{}
}

/*
CloudDiagnosticsMarkCloudPolicyLatestInternalServerError describes a response with status code 500, with default header values.

Internal Server Error. The API gateway experienced an unexpected condition. Specific error condition is indicated in error codes.
*/
type CloudDiagnosticsMarkCloudPolicyLatestInternalServerError struct {
	Payload *swagger_models.ZsrvResponse
}

// IsSuccess returns true when this cloud diagnostics mark cloud policy latest internal server error response has a 2xx status code
func (o *CloudDiagnosticsMarkCloudPolicyLatestInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this cloud diagnostics mark cloud policy latest internal server error response has a 3xx status code
func (o *CloudDiagnosticsMarkCloudPolicyLatestInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this cloud diagnostics mark cloud policy latest internal server error response has a 4xx status code
func (o *CloudDiagnosticsMarkCloudPolicyLatestInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this cloud diagnostics mark cloud policy latest internal server error response has a 5xx status code
func (o *CloudDiagnosticsMarkCloudPolicyLatestInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this cloud diagnostics mark cloud policy latest internal server error response a status code equal to that given
func (o *CloudDiagnosticsMarkCloudPolicyLatestInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *CloudDiagnosticsMarkCloudPolicyLatestInternalServerError) Error() string {
	return fmt.Sprintf("[PUT /v1/cloud/policies][%d] cloudDiagnosticsMarkCloudPolicyLatestInternalServerError  %+v", 500, o.Payload)
}

func (o *CloudDiagnosticsMarkCloudPolicyLatestInternalServerError) String() string {
	return fmt.Sprintf("[PUT /v1/cloud/policies][%d] cloudDiagnosticsMarkCloudPolicyLatestInternalServerError  %+v", 500, o.Payload)
}

func (o *CloudDiagnosticsMarkCloudPolicyLatestInternalServerError) GetPayload() *swagger_models.ZsrvResponse {
	return o.Payload
}

func (o *CloudDiagnosticsMarkCloudPolicyLatestInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(swagger_models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCloudDiagnosticsMarkCloudPolicyLatestGatewayTimeout creates a CloudDiagnosticsMarkCloudPolicyLatestGatewayTimeout with default headers values
func NewCloudDiagnosticsMarkCloudPolicyLatestGatewayTimeout() *CloudDiagnosticsMarkCloudPolicyLatestGatewayTimeout {
	return &CloudDiagnosticsMarkCloudPolicyLatestGatewayTimeout{}
}

/*
CloudDiagnosticsMarkCloudPolicyLatestGatewayTimeout describes a response with status code 504, with default header values.

Gateway Timeout. The API gateway did not receive a timely response from an upstream microservice it needed to communicate with in order to complete the request.
*/
type CloudDiagnosticsMarkCloudPolicyLatestGatewayTimeout struct {
	Payload *swagger_models.ZsrvResponse
}

// IsSuccess returns true when this cloud diagnostics mark cloud policy latest gateway timeout response has a 2xx status code
func (o *CloudDiagnosticsMarkCloudPolicyLatestGatewayTimeout) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this cloud diagnostics mark cloud policy latest gateway timeout response has a 3xx status code
func (o *CloudDiagnosticsMarkCloudPolicyLatestGatewayTimeout) IsRedirect() bool {
	return false
}

// IsClientError returns true when this cloud diagnostics mark cloud policy latest gateway timeout response has a 4xx status code
func (o *CloudDiagnosticsMarkCloudPolicyLatestGatewayTimeout) IsClientError() bool {
	return false
}

// IsServerError returns true when this cloud diagnostics mark cloud policy latest gateway timeout response has a 5xx status code
func (o *CloudDiagnosticsMarkCloudPolicyLatestGatewayTimeout) IsServerError() bool {
	return true
}

// IsCode returns true when this cloud diagnostics mark cloud policy latest gateway timeout response a status code equal to that given
func (o *CloudDiagnosticsMarkCloudPolicyLatestGatewayTimeout) IsCode(code int) bool {
	return code == 504
}

func (o *CloudDiagnosticsMarkCloudPolicyLatestGatewayTimeout) Error() string {
	return fmt.Sprintf("[PUT /v1/cloud/policies][%d] cloudDiagnosticsMarkCloudPolicyLatestGatewayTimeout  %+v", 504, o.Payload)
}

func (o *CloudDiagnosticsMarkCloudPolicyLatestGatewayTimeout) String() string {
	return fmt.Sprintf("[PUT /v1/cloud/policies][%d] cloudDiagnosticsMarkCloudPolicyLatestGatewayTimeout  %+v", 504, o.Payload)
}

func (o *CloudDiagnosticsMarkCloudPolicyLatestGatewayTimeout) GetPayload() *swagger_models.ZsrvResponse {
	return o.Payload
}

func (o *CloudDiagnosticsMarkCloudPolicyLatestGatewayTimeout) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(swagger_models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCloudDiagnosticsMarkCloudPolicyLatestDefault creates a CloudDiagnosticsMarkCloudPolicyLatestDefault with default headers values
func NewCloudDiagnosticsMarkCloudPolicyLatestDefault(code int) *CloudDiagnosticsMarkCloudPolicyLatestDefault {
	return &CloudDiagnosticsMarkCloudPolicyLatestDefault{
		_statusCode: code,
	}
}

/*
CloudDiagnosticsMarkCloudPolicyLatestDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type CloudDiagnosticsMarkCloudPolicyLatestDefault struct {
	_statusCode int

	Payload *swagger_models.GooglerpcStatus
}

// Code gets the status code for the cloud diagnostics mark cloud policy latest default response
func (o *CloudDiagnosticsMarkCloudPolicyLatestDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this cloud diagnostics mark cloud policy latest default response has a 2xx status code
func (o *CloudDiagnosticsMarkCloudPolicyLatestDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this cloud diagnostics mark cloud policy latest default response has a 3xx status code
func (o *CloudDiagnosticsMarkCloudPolicyLatestDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this cloud diagnostics mark cloud policy latest default response has a 4xx status code
func (o *CloudDiagnosticsMarkCloudPolicyLatestDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this cloud diagnostics mark cloud policy latest default response has a 5xx status code
func (o *CloudDiagnosticsMarkCloudPolicyLatestDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this cloud diagnostics mark cloud policy latest default response a status code equal to that given
func (o *CloudDiagnosticsMarkCloudPolicyLatestDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *CloudDiagnosticsMarkCloudPolicyLatestDefault) Error() string {
	return fmt.Sprintf("[PUT /v1/cloud/policies][%d] CloudDiagnostics_MarkCloudPolicyLatest default  %+v", o._statusCode, o.Payload)
}

func (o *CloudDiagnosticsMarkCloudPolicyLatestDefault) String() string {
	return fmt.Sprintf("[PUT /v1/cloud/policies][%d] CloudDiagnostics_MarkCloudPolicyLatest default  %+v", o._statusCode, o.Payload)
}

func (o *CloudDiagnosticsMarkCloudPolicyLatestDefault) GetPayload() *swagger_models.GooglerpcStatus {
	return o.Payload
}

func (o *CloudDiagnosticsMarkCloudPolicyLatestDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(swagger_models.GooglerpcStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
