// Copyright (c) 2018-2021 Zededa, Inc.\n// SPDX-License-Identifier: Apache-2.0\n
// Code generated by go-swagger; DO NOT EDIT.

package edge_application_instance_status

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/zededa/zedcloud-api/swagger_models"
)

// EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2Reader is a Reader for the EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2 structure.
type EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewEdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewEdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2Unauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewEdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2Forbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewEdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2NotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewEdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2InternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 504:
		result := NewEdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2GatewayTimeout()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewEdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2Default(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewEdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2OK creates a EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2OK with default headers values
func NewEdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2OK() *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2OK {
	return &EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2OK{}
}

/*
EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2OK describes a response with status code 200, with default header values.

A successful response.
*/
type EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2OK struct {
	Payload *swagger_models.TopTalkersResponse
}

// IsSuccess returns true when this edge application instance status get edge application instance top talkers2 o k response has a 2xx status code
func (o *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2OK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this edge application instance status get edge application instance top talkers2 o k response has a 3xx status code
func (o *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2OK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this edge application instance status get edge application instance top talkers2 o k response has a 4xx status code
func (o *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2OK) IsClientError() bool {
	return false
}

// IsServerError returns true when this edge application instance status get edge application instance top talkers2 o k response has a 5xx status code
func (o *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2OK) IsServerError() bool {
	return false
}

// IsCode returns true when this edge application instance status get edge application instance top talkers2 o k response a status code equal to that given
func (o *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2OK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the edge application instance status get edge application instance top talkers2 o k response
func (o *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2OK) Code() int {
	return 200
}

func (o *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2OK) Error() string {
	return fmt.Sprintf("[GET /v1/apps/instances/name/{name}/flowlog/toptalkers][%d] edgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2OK  %+v", 200, o.Payload)
}

func (o *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2OK) String() string {
	return fmt.Sprintf("[GET /v1/apps/instances/name/{name}/flowlog/toptalkers][%d] edgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2OK  %+v", 200, o.Payload)
}

func (o *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2OK) GetPayload() *swagger_models.TopTalkersResponse {
	return o.Payload
}

func (o *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(swagger_models.TopTalkersResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2Unauthorized creates a EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2Unauthorized with default headers values
func NewEdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2Unauthorized() *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2Unauthorized {
	return &EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2Unauthorized{}
}

/*
EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2Unauthorized describes a response with status code 401, with default header values.

Unauthorized. The API gateway did not process the request because it lacks valid authentication credentials for the target resource. The request header has either no authorization details or an authorization that has been refused.
*/
type EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2Unauthorized struct {
	Payload *swagger_models.ZsrvResponse
}

// IsSuccess returns true when this edge application instance status get edge application instance top talkers2 unauthorized response has a 2xx status code
func (o *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2Unauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this edge application instance status get edge application instance top talkers2 unauthorized response has a 3xx status code
func (o *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2Unauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this edge application instance status get edge application instance top talkers2 unauthorized response has a 4xx status code
func (o *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2Unauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this edge application instance status get edge application instance top talkers2 unauthorized response has a 5xx status code
func (o *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2Unauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this edge application instance status get edge application instance top talkers2 unauthorized response a status code equal to that given
func (o *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2Unauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the edge application instance status get edge application instance top talkers2 unauthorized response
func (o *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2Unauthorized) Code() int {
	return 401
}

func (o *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2Unauthorized) Error() string {
	return fmt.Sprintf("[GET /v1/apps/instances/name/{name}/flowlog/toptalkers][%d] edgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2Unauthorized  %+v", 401, o.Payload)
}

func (o *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2Unauthorized) String() string {
	return fmt.Sprintf("[GET /v1/apps/instances/name/{name}/flowlog/toptalkers][%d] edgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2Unauthorized  %+v", 401, o.Payload)
}

func (o *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2Unauthorized) GetPayload() *swagger_models.ZsrvResponse {
	return o.Payload
}

func (o *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2Unauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(swagger_models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2Forbidden creates a EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2Forbidden with default headers values
func NewEdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2Forbidden() *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2Forbidden {
	return &EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2Forbidden{}
}

/*
EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2Forbidden describes a response with status code 403, with default header values.

Forbidden. The API gateway did not process the request because the requestor does not have application level access permission for the operation or does not have access scope to the project.
*/
type EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2Forbidden struct {
	Payload *swagger_models.ZsrvResponse
}

// IsSuccess returns true when this edge application instance status get edge application instance top talkers2 forbidden response has a 2xx status code
func (o *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2Forbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this edge application instance status get edge application instance top talkers2 forbidden response has a 3xx status code
func (o *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2Forbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this edge application instance status get edge application instance top talkers2 forbidden response has a 4xx status code
func (o *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2Forbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this edge application instance status get edge application instance top talkers2 forbidden response has a 5xx status code
func (o *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2Forbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this edge application instance status get edge application instance top talkers2 forbidden response a status code equal to that given
func (o *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2Forbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the edge application instance status get edge application instance top talkers2 forbidden response
func (o *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2Forbidden) Code() int {
	return 403
}

func (o *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2Forbidden) Error() string {
	return fmt.Sprintf("[GET /v1/apps/instances/name/{name}/flowlog/toptalkers][%d] edgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2Forbidden  %+v", 403, o.Payload)
}

func (o *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2Forbidden) String() string {
	return fmt.Sprintf("[GET /v1/apps/instances/name/{name}/flowlog/toptalkers][%d] edgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2Forbidden  %+v", 403, o.Payload)
}

func (o *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2Forbidden) GetPayload() *swagger_models.ZsrvResponse {
	return o.Payload
}

func (o *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2Forbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(swagger_models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2NotFound creates a EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2NotFound with default headers values
func NewEdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2NotFound() *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2NotFound {
	return &EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2NotFound{}
}

/*
EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2NotFound describes a response with status code 404, with default header values.

Not Found. The API gateway did not process the request because the requested resource could not be found.
*/
type EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2NotFound struct {
	Payload *swagger_models.ZsrvResponse
}

// IsSuccess returns true when this edge application instance status get edge application instance top talkers2 not found response has a 2xx status code
func (o *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2NotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this edge application instance status get edge application instance top talkers2 not found response has a 3xx status code
func (o *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2NotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this edge application instance status get edge application instance top talkers2 not found response has a 4xx status code
func (o *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2NotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this edge application instance status get edge application instance top talkers2 not found response has a 5xx status code
func (o *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2NotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this edge application instance status get edge application instance top talkers2 not found response a status code equal to that given
func (o *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2NotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the edge application instance status get edge application instance top talkers2 not found response
func (o *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2NotFound) Code() int {
	return 404
}

func (o *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2NotFound) Error() string {
	return fmt.Sprintf("[GET /v1/apps/instances/name/{name}/flowlog/toptalkers][%d] edgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2NotFound  %+v", 404, o.Payload)
}

func (o *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2NotFound) String() string {
	return fmt.Sprintf("[GET /v1/apps/instances/name/{name}/flowlog/toptalkers][%d] edgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2NotFound  %+v", 404, o.Payload)
}

func (o *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2NotFound) GetPayload() *swagger_models.ZsrvResponse {
	return o.Payload
}

func (o *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2NotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(swagger_models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2InternalServerError creates a EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2InternalServerError with default headers values
func NewEdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2InternalServerError() *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2InternalServerError {
	return &EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2InternalServerError{}
}

/*
EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2InternalServerError describes a response with status code 500, with default header values.

Internal Server Error. The API gateway experienced an unexpected condition. Specific error condition is indicated in error codes.
*/
type EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2InternalServerError struct {
	Payload *swagger_models.ZsrvResponse
}

// IsSuccess returns true when this edge application instance status get edge application instance top talkers2 internal server error response has a 2xx status code
func (o *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2InternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this edge application instance status get edge application instance top talkers2 internal server error response has a 3xx status code
func (o *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2InternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this edge application instance status get edge application instance top talkers2 internal server error response has a 4xx status code
func (o *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2InternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this edge application instance status get edge application instance top talkers2 internal server error response has a 5xx status code
func (o *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2InternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this edge application instance status get edge application instance top talkers2 internal server error response a status code equal to that given
func (o *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2InternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the edge application instance status get edge application instance top talkers2 internal server error response
func (o *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2InternalServerError) Code() int {
	return 500
}

func (o *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2InternalServerError) Error() string {
	return fmt.Sprintf("[GET /v1/apps/instances/name/{name}/flowlog/toptalkers][%d] edgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2InternalServerError  %+v", 500, o.Payload)
}

func (o *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2InternalServerError) String() string {
	return fmt.Sprintf("[GET /v1/apps/instances/name/{name}/flowlog/toptalkers][%d] edgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2InternalServerError  %+v", 500, o.Payload)
}

func (o *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2InternalServerError) GetPayload() *swagger_models.ZsrvResponse {
	return o.Payload
}

func (o *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2InternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(swagger_models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2GatewayTimeout creates a EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2GatewayTimeout with default headers values
func NewEdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2GatewayTimeout() *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2GatewayTimeout {
	return &EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2GatewayTimeout{}
}

/*
EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2GatewayTimeout describes a response with status code 504, with default header values.

Gateway Timeout. The API gateway did not receive a timely response from an upstream microservice it needed to communicate with in order to complete the request.
*/
type EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2GatewayTimeout struct {
	Payload *swagger_models.ZsrvResponse
}

// IsSuccess returns true when this edge application instance status get edge application instance top talkers2 gateway timeout response has a 2xx status code
func (o *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2GatewayTimeout) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this edge application instance status get edge application instance top talkers2 gateway timeout response has a 3xx status code
func (o *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2GatewayTimeout) IsRedirect() bool {
	return false
}

// IsClientError returns true when this edge application instance status get edge application instance top talkers2 gateway timeout response has a 4xx status code
func (o *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2GatewayTimeout) IsClientError() bool {
	return false
}

// IsServerError returns true when this edge application instance status get edge application instance top talkers2 gateway timeout response has a 5xx status code
func (o *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2GatewayTimeout) IsServerError() bool {
	return true
}

// IsCode returns true when this edge application instance status get edge application instance top talkers2 gateway timeout response a status code equal to that given
func (o *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2GatewayTimeout) IsCode(code int) bool {
	return code == 504
}

// Code gets the status code for the edge application instance status get edge application instance top talkers2 gateway timeout response
func (o *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2GatewayTimeout) Code() int {
	return 504
}

func (o *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2GatewayTimeout) Error() string {
	return fmt.Sprintf("[GET /v1/apps/instances/name/{name}/flowlog/toptalkers][%d] edgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2GatewayTimeout  %+v", 504, o.Payload)
}

func (o *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2GatewayTimeout) String() string {
	return fmt.Sprintf("[GET /v1/apps/instances/name/{name}/flowlog/toptalkers][%d] edgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2GatewayTimeout  %+v", 504, o.Payload)
}

func (o *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2GatewayTimeout) GetPayload() *swagger_models.ZsrvResponse {
	return o.Payload
}

func (o *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2GatewayTimeout) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(swagger_models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2Default creates a EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2Default with default headers values
func NewEdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2Default(code int) *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2Default {
	return &EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2Default{
		_statusCode: code,
	}
}

/*
EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2Default describes a response with status code -1, with default header values.

An unexpected error response.
*/
type EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2Default struct {
	_statusCode int

	Payload *swagger_models.GooglerpcStatus
}

// IsSuccess returns true when this edge application instance status get edge application instance top talkers2 default response has a 2xx status code
func (o *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2Default) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this edge application instance status get edge application instance top talkers2 default response has a 3xx status code
func (o *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2Default) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this edge application instance status get edge application instance top talkers2 default response has a 4xx status code
func (o *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2Default) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this edge application instance status get edge application instance top talkers2 default response has a 5xx status code
func (o *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2Default) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this edge application instance status get edge application instance top talkers2 default response a status code equal to that given
func (o *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2Default) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the edge application instance status get edge application instance top talkers2 default response
func (o *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2Default) Code() int {
	return o._statusCode
}

func (o *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2Default) Error() string {
	return fmt.Sprintf("[GET /v1/apps/instances/name/{name}/flowlog/toptalkers][%d] EdgeApplicationInstanceStatus_GetEdgeApplicationInstanceTopTalkers2 default  %+v", o._statusCode, o.Payload)
}

func (o *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2Default) String() string {
	return fmt.Sprintf("[GET /v1/apps/instances/name/{name}/flowlog/toptalkers][%d] EdgeApplicationInstanceStatus_GetEdgeApplicationInstanceTopTalkers2 default  %+v", o._statusCode, o.Payload)
}

func (o *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2Default) GetPayload() *swagger_models.GooglerpcStatus {
	return o.Payload
}

func (o *EdgeApplicationInstanceStatusGetEdgeApplicationInstanceTopTalkers2Default) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(swagger_models.GooglerpcStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
