// Copyright (c) 2018-2021 Zededa, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by go-swagger; DO NOT EDIT.

package edge_network_instance_status

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/zededa/zedcloud-api/swagger_models"
)

// EdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameReader is a Reader for the EdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByName structure.
type EdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewEdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewEdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewEdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewEdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewEdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 504:
		result := NewEdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameGatewayTimeout()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewEdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewEdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameOK creates a EdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameOK with default headers values
func NewEdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameOK() *EdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameOK {
	return &EdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameOK{}
}

/* EdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameOK describes a response with status code 200, with default header values.

A successful response.
*/
type EdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameOK struct {
	Payload *swagger_models.NetInstStatusMsg
}

func (o *EdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameOK) Error() string {
	return fmt.Sprintf("[GET /v1/netinsts/name/{name}/status][%d] edgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameOK  %+v", 200, o.Payload)
}
func (o *EdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameOK) GetPayload() *swagger_models.NetInstStatusMsg {
	return o.Payload
}

func (o *EdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(swagger_models.NetInstStatusMsg)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameUnauthorized creates a EdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameUnauthorized with default headers values
func NewEdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameUnauthorized() *EdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameUnauthorized {
	return &EdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameUnauthorized{}
}

/* EdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameUnauthorized describes a response with status code 401, with default header values.

Unauthorized. The API gateway did not process the request because it lacks valid authentication credentials for the target resource. The request header has either no authorization details or an authorization that has been refused.
*/
type EdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameUnauthorized struct {
	Payload *swagger_models.ZsrvResponse
}

func (o *EdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameUnauthorized) Error() string {
	return fmt.Sprintf("[GET /v1/netinsts/name/{name}/status][%d] edgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameUnauthorized  %+v", 401, o.Payload)
}
func (o *EdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameUnauthorized) GetPayload() *swagger_models.ZsrvResponse {
	return o.Payload
}

func (o *EdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(swagger_models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameForbidden creates a EdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameForbidden with default headers values
func NewEdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameForbidden() *EdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameForbidden {
	return &EdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameForbidden{}
}

/* EdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameForbidden describes a response with status code 403, with default header values.

Forbidden. The API gateway did not process the request because the requestor does not have edge-node level access permission for the operation or does not have access scope to the project.
*/
type EdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameForbidden struct {
	Payload *swagger_models.ZsrvResponse
}

func (o *EdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameForbidden) Error() string {
	return fmt.Sprintf("[GET /v1/netinsts/name/{name}/status][%d] edgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameForbidden  %+v", 403, o.Payload)
}
func (o *EdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameForbidden) GetPayload() *swagger_models.ZsrvResponse {
	return o.Payload
}

func (o *EdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(swagger_models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameNotFound creates a EdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameNotFound with default headers values
func NewEdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameNotFound() *EdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameNotFound {
	return &EdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameNotFound{}
}

/* EdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameNotFound describes a response with status code 404, with default header values.

Not Found. The API gateway did not process the request because the requested resource could not be found.
*/
type EdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameNotFound struct {
	Payload *swagger_models.ZsrvResponse
}

func (o *EdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameNotFound) Error() string {
	return fmt.Sprintf("[GET /v1/netinsts/name/{name}/status][%d] edgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameNotFound  %+v", 404, o.Payload)
}
func (o *EdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameNotFound) GetPayload() *swagger_models.ZsrvResponse {
	return o.Payload
}

func (o *EdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(swagger_models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameInternalServerError creates a EdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameInternalServerError with default headers values
func NewEdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameInternalServerError() *EdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameInternalServerError {
	return &EdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameInternalServerError{}
}

/* EdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameInternalServerError describes a response with status code 500, with default header values.

Internal Server Error. The API gateway experienced an unexpected condition. Specific error condition is indicated in error codes.
*/
type EdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameInternalServerError struct {
	Payload *swagger_models.ZsrvResponse
}

func (o *EdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameInternalServerError) Error() string {
	return fmt.Sprintf("[GET /v1/netinsts/name/{name}/status][%d] edgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameInternalServerError  %+v", 500, o.Payload)
}
func (o *EdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameInternalServerError) GetPayload() *swagger_models.ZsrvResponse {
	return o.Payload
}

func (o *EdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(swagger_models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameGatewayTimeout creates a EdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameGatewayTimeout with default headers values
func NewEdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameGatewayTimeout() *EdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameGatewayTimeout {
	return &EdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameGatewayTimeout{}
}

/* EdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameGatewayTimeout describes a response with status code 504, with default header values.

Gateway Timeout. The API gateway did not receive a timely response from an upstream microservice it needed to communicate with in order to complete the request.
*/
type EdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameGatewayTimeout struct {
	Payload *swagger_models.ZsrvResponse
}

func (o *EdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameGatewayTimeout) Error() string {
	return fmt.Sprintf("[GET /v1/netinsts/name/{name}/status][%d] edgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameGatewayTimeout  %+v", 504, o.Payload)
}
func (o *EdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameGatewayTimeout) GetPayload() *swagger_models.ZsrvResponse {
	return o.Payload
}

func (o *EdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameGatewayTimeout) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(swagger_models.ZsrvResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameDefault creates a EdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameDefault with default headers values
func NewEdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameDefault(code int) *EdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameDefault {
	return &EdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameDefault{
		_statusCode: code,
	}
}

/* EdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type EdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameDefault struct {
	_statusCode int

	Payload *swagger_models.GooglerpcStatus
}

// Code gets the status code for the edge network instance status get edge network instance status by name default response
func (o *EdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameDefault) Code() int {
	return o._statusCode
}

func (o *EdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameDefault) Error() string {
	return fmt.Sprintf("[GET /v1/netinsts/name/{name}/status][%d] EdgeNetworkInstanceStatus_GetEdgeNetworkInstanceStatusByName default  %+v", o._statusCode, o.Payload)
}
func (o *EdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameDefault) GetPayload() *swagger_models.GooglerpcStatus {
	return o.Payload
}

func (o *EdgeNetworkInstanceStatusGetEdgeNetworkInstanceStatusByNameDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(swagger_models.GooglerpcStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
