// Copyright (c) 2018-2021 Zededa, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by go-swagger; DO NOT EDIT.

package edge_application_configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/zededa/zedcloud-api/swagger_models"
)

// NewCreateEdgeApplicationBundleParams creates a new CreateEdgeApplicationBundleParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateEdgeApplicationBundleParams() *CreateEdgeApplicationBundleParams {
	return &CreateEdgeApplicationBundleParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateEdgeApplicationBundleParamsWithTimeout creates a new CreateEdgeApplicationBundleParams object
// with the ability to set a timeout on a request.
func NewCreateEdgeApplicationBundleParamsWithTimeout(timeout time.Duration) *CreateEdgeApplicationBundleParams {
	return &CreateEdgeApplicationBundleParams{
		timeout: timeout,
	}
}

// NewCreateEdgeApplicationBundleParamsWithContext creates a new CreateEdgeApplicationBundleParams object
// with the ability to set a context for a request.
func NewCreateEdgeApplicationBundleParamsWithContext(ctx context.Context) *CreateEdgeApplicationBundleParams {
	return &CreateEdgeApplicationBundleParams{
		Context: ctx,
	}
}

// NewCreateEdgeApplicationBundleParamsWithHTTPClient creates a new CreateEdgeApplicationBundleParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateEdgeApplicationBundleParamsWithHTTPClient(client *http.Client) *CreateEdgeApplicationBundleParams {
	return &CreateEdgeApplicationBundleParams{
		HTTPClient: client,
	}
}

/* CreateEdgeApplicationBundleParams contains all the parameters to send to the API endpoint
   for the create edge application bundle operation.

   Typically these are written to a http.Request.
*/
type CreateEdgeApplicationBundleParams struct {

	/* XRequestID.

	   User-Agent specified id to track a request
	*/
	XRequestID *string

	// Body.
	Body *swagger_models.App

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create edge application bundle params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateEdgeApplicationBundleParams) WithDefaults() *CreateEdgeApplicationBundleParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create edge application bundle params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateEdgeApplicationBundleParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create edge application bundle params
func (o *CreateEdgeApplicationBundleParams) WithTimeout(timeout time.Duration) *CreateEdgeApplicationBundleParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create edge application bundle params
func (o *CreateEdgeApplicationBundleParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create edge application bundle params
func (o *CreateEdgeApplicationBundleParams) WithContext(ctx context.Context) *CreateEdgeApplicationBundleParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create edge application bundle params
func (o *CreateEdgeApplicationBundleParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create edge application bundle params
func (o *CreateEdgeApplicationBundleParams) WithHTTPClient(client *http.Client) *CreateEdgeApplicationBundleParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create edge application bundle params
func (o *CreateEdgeApplicationBundleParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXRequestID adds the xRequestID to the create edge application bundle params
func (o *CreateEdgeApplicationBundleParams) WithXRequestID(xRequestID *string) *CreateEdgeApplicationBundleParams {
	o.SetXRequestID(xRequestID)
	return o
}

// SetXRequestID adds the xRequestId to the create edge application bundle params
func (o *CreateEdgeApplicationBundleParams) SetXRequestID(xRequestID *string) {
	o.XRequestID = xRequestID
}

// WithBody adds the body to the create edge application bundle params
func (o *CreateEdgeApplicationBundleParams) WithBody(body *swagger_models.App) *CreateEdgeApplicationBundleParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create edge application bundle params
func (o *CreateEdgeApplicationBundleParams) SetBody(body *swagger_models.App) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateEdgeApplicationBundleParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XRequestID != nil {

		// header param X-Request-Id
		if err := r.SetHeaderParam("X-Request-Id", *o.XRequestID); err != nil {
			return err
		}
	}
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
