// Copyright (c) 2018-2021 Zededa, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by go-swagger; DO NOT EDIT.

package edge_network_instance_configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/zededa/zedcloud-api/swagger_models"
)

// NewUpdateEdgeNetworkInstanceParams creates a new UpdateEdgeNetworkInstanceParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateEdgeNetworkInstanceParams() *UpdateEdgeNetworkInstanceParams {
	return &UpdateEdgeNetworkInstanceParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateEdgeNetworkInstanceParamsWithTimeout creates a new UpdateEdgeNetworkInstanceParams object
// with the ability to set a timeout on a request.
func NewUpdateEdgeNetworkInstanceParamsWithTimeout(timeout time.Duration) *UpdateEdgeNetworkInstanceParams {
	return &UpdateEdgeNetworkInstanceParams{
		timeout: timeout,
	}
}

// NewUpdateEdgeNetworkInstanceParamsWithContext creates a new UpdateEdgeNetworkInstanceParams object
// with the ability to set a context for a request.
func NewUpdateEdgeNetworkInstanceParamsWithContext(ctx context.Context) *UpdateEdgeNetworkInstanceParams {
	return &UpdateEdgeNetworkInstanceParams{
		Context: ctx,
	}
}

// NewUpdateEdgeNetworkInstanceParamsWithHTTPClient creates a new UpdateEdgeNetworkInstanceParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateEdgeNetworkInstanceParamsWithHTTPClient(client *http.Client) *UpdateEdgeNetworkInstanceParams {
	return &UpdateEdgeNetworkInstanceParams{
		HTTPClient: client,
	}
}

/* UpdateEdgeNetworkInstanceParams contains all the parameters to send to the API endpoint
   for the update edge network instance operation.

   Typically these are written to a http.Request.
*/
type UpdateEdgeNetworkInstanceParams struct {

	/* XRequestID.

	   User-Agent specified id to track a request
	*/
	XRequestID *string

	// Body.
	Body *swagger_models.NetInstConfig

	/* ID.

	   System defined universally unique Id of the network instance
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update edge network instance params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateEdgeNetworkInstanceParams) WithDefaults() *UpdateEdgeNetworkInstanceParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update edge network instance params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateEdgeNetworkInstanceParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update edge network instance params
func (o *UpdateEdgeNetworkInstanceParams) WithTimeout(timeout time.Duration) *UpdateEdgeNetworkInstanceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update edge network instance params
func (o *UpdateEdgeNetworkInstanceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update edge network instance params
func (o *UpdateEdgeNetworkInstanceParams) WithContext(ctx context.Context) *UpdateEdgeNetworkInstanceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update edge network instance params
func (o *UpdateEdgeNetworkInstanceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update edge network instance params
func (o *UpdateEdgeNetworkInstanceParams) WithHTTPClient(client *http.Client) *UpdateEdgeNetworkInstanceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update edge network instance params
func (o *UpdateEdgeNetworkInstanceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXRequestID adds the xRequestID to the update edge network instance params
func (o *UpdateEdgeNetworkInstanceParams) WithXRequestID(xRequestID *string) *UpdateEdgeNetworkInstanceParams {
	o.SetXRequestID(xRequestID)
	return o
}

// SetXRequestID adds the xRequestId to the update edge network instance params
func (o *UpdateEdgeNetworkInstanceParams) SetXRequestID(xRequestID *string) {
	o.XRequestID = xRequestID
}

// WithBody adds the body to the update edge network instance params
func (o *UpdateEdgeNetworkInstanceParams) WithBody(body *swagger_models.NetInstConfig) *UpdateEdgeNetworkInstanceParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update edge network instance params
func (o *UpdateEdgeNetworkInstanceParams) SetBody(body *swagger_models.NetInstConfig) {
	o.Body = body
}

// WithID adds the id to the update edge network instance params
func (o *UpdateEdgeNetworkInstanceParams) WithID(id string) *UpdateEdgeNetworkInstanceParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the update edge network instance params
func (o *UpdateEdgeNetworkInstanceParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateEdgeNetworkInstanceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XRequestID != nil {

		// header param X-Request-Id
		if err := r.SetHeaderParam("X-Request-Id", *o.XRequestID); err != nil {
			return err
		}
	}
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
